// AI_ATC's workflows, traced from its source code (numbers are the code's defaults).
import type { WorkflowSet } from './types';

const en: WorkflowSet = {
  intro:
    'AI_ATC runs nine workflows alongside X-Plane. Your aircraft is followed every second; your radio calls are understood by local AI, but every answer is built by rules and navigation data, and checked before it is spoken. Pick one to follow it step by step.',
  workflows: [
    {
      id: 'link',
      title: 'Simulator link',
      trigger: 'Every frame in X-Plane; sent every second',
      summary: 'A plugin inside X-Plane reads your aircraft, so the controller always knows where you are and what you are doing.',
      steps: [
        { actor: 'sim', label: 'Read your aircraft, every frame', detail: 'Position, speeds, headings, radios, weather, landing gear and flaps.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Which phase of flight?',
          detail: 'Decided by fixed rules, not by AI.',
          branches: [
            { when: 'Under 5 kt', then: 'Parked.' },
            { when: 'Under 30 kt', then: 'Taxi.' },
            { when: 'Rolling for take-off', then: 'Take-off roll.' },
            { when: 'Below 1,500 ft and climbing', then: 'Departure.' },
            { when: 'Below 3,000 ft, descending, gear down', then: 'Approach.' },
            { when: 'Climbing or descending over 500 ft a minute', then: 'Climb or descent.' },
          ],
          yes: 'Otherwise: cruise',
        },
        { kind: 'schedule', actor: 'sim', label: 'Exchange data with the controller', detail: 'Your aircraft’s state is sent every second, nearby traffic is fetched every half second, and controller commands are picked up every second.' },
        { kind: 'schedule', actor: 'ext', label: 'Add the real weather', detail: 'Every 5 minutes, a real METAR (the airport’s official weather report) is added.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Heard from the simulator in 30 seconds?',
          branches: [{ when: 'No', then: 'Marked as disconnected.', tone: 'warn' }],
          yes: 'Connected',
        },
        { actor: 'app', label: 'Your position is known to the controller', goto: 'understand' },
      ],
      outputs: ['Your position, speed and phase of flight', 'Live weather'],
      feeds: ['understand', 'traffic', 'plan'],
    },
    {
      id: 'speak',
      title: 'Speak',
      trigger: 'When you hold push-to-talk',
      summary: 'Your radio call is recorded and turned into text by local speech recognition.',
      steps: [
        { actor: 'you', label: 'Hold push-to-talk', detail: 'In the web portal or inside the simulator.' },
        { actor: 'app', label: 'Record your call', detail: 'Recorded at 16 kHz while you hold the button.' },
        { actor: 'ai', label: 'Turn your voice into text', detail: 'Local speech recognition (Whisper) writes down what you said.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Was anything said?',
          branches: [{ when: 'No', then: 'You see “No speech detected”.', tone: 'warn' }],
          yes: 'The text of your call',
        },
        { actor: 'you', label: 'Or type it', detail: 'You can type a call instead of speaking it.' },
        { actor: 'app', label: 'Your words go to the controller', goto: 'understand' },
      ],
      outputs: ['The text of your radio call'],
      feeds: ['understand'],
    },
    {
      id: 'understand',
      title: 'Understand the request',
      trigger: 'After every call you make',
      summary: 'The local AI only sorts what you said into one of 14 request types; it never writes the answer.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Are your position and airport known?',
          branches: [{ when: 'No', then: '“Standby” (wait), with the reason.', tone: 'warn' }],
          yes: 'Known',
        },
        {
          actor: 'ai',
          label: 'Sort the call into one of 14 request types',
          detail: 'The local AI only picks the type, set to give the same answer for the same words, with a 20-second limit.',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Word rules have the last say',
          branches: [
            { when: 'You said “mayday”', then: 'Treated as an emergency.', tone: 'warn' },
            { when: 'You repeated an instruction', then: 'Treated as a readback.', goto: 'readback' },
            { when: '“Say again” or a level change', then: 'Recognised by the words themselves.' },
          ],
          yes: 'Otherwise the AI’s choice stands',
        },
        { actor: 'app', label: 'Read your callsign', detail: 'Taken from your own words, never invented.' },
        { actor: 'app', label: 'The request is passed on', goto: 'decide' },
      ],
      outputs: ['One of 14 request types', 'Your callsign'],
      feeds: ['decide', 'readback'],
    },
    {
      id: 'decide',
      title: 'Decide the answer',
      trigger: 'For every understood request',
      summary: 'Rules and the navigation data build the controller’s answer; no text is written by AI.',
      steps: [
        { actor: 'app', label: 'Pick the runway in use', detail: 'The airport’s own traffic-flow rules come first; otherwise the wind decides.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'What does the wind allow?',
          branches: [
            { when: 'Tailwind over 10 kt', then: 'That runway is excluded.', tone: 'bad' },
            { when: 'Calm, under 3 kt', then: 'The longest runway.' },
          ],
          yes: 'Otherwise: the runway with the most headwind',
        },
        { actor: 'app', label: 'Keep the runway steady', detail: 'A runway stays in use at least 10 minutes and changes only for 3 kt more headwind.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Are you on the right frequency?',
          branches: [{ when: 'Off by more than 0.012 MHz', then: '“Wrong frequency”.', tone: 'bad' }],
          yes: 'Right frequency',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'What did you ask for?',
          branches: [
            { when: 'Taxi', then: 'A route along the airport’s taxiways to the holding point, where you wait before the runway.' },
            { when: 'IFR clearance', then: 'For a flight on instruments: the departure procedure (SID, the published route out) from your route, a squawk (your transponder code) and the departure frequency.' },
            { when: 'Take-off', then: 'Only after the wake gap: the wait for the turbulence behind the last departure to clear.' },
            { when: 'Landing', then: 'Your sequence number, the traffic ahead and the wind.' },
            { when: 'Approach', then: 'The best published approach: ILS (the instrument landing system) first, then GLS, then LOC.' },
            { when: 'Descent', then: 'Never below the approach’s first altitude.' },
          ],
        },
        { actor: 'store', label: 'Every detail from the navigation data', detail: 'Runways, taxiways, procedures and frequencies come from the real data for that airport.' },
        { actor: 'app', label: 'The answer goes to the checks', goto: 'check' },
      ],
      outputs: ['Runway in use', 'Taxi route, clearance or landing sequence', 'An answer built by rules'],
      feeds: ['check'],
    },
    {
      id: 'check',
      title: 'Check before speaking',
      trigger: 'Before anything is spoken',
      summary: 'Three checks gate every answer; if any fails, you hear “standby” with the reason and nothing is transmitted.',
      steps: [
        {
          kind: 'decision',
          actor: 'store',
          label: 'Does everything exist at that airport?',
          detail: 'Every runway, taxiway, procedure, fix (a named point in the sky) and frequency.',
          branches: [{ when: 'No', then: '“Standby”, with the reason; nothing is transmitted.', tone: 'warn' }],
          yes: 'All real',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is the message well formed?',
          detail: 'Your callsign; altitude 100–60,000 ft in hundreds; heading 1–360; speed 60–400 kt; a valid squawk.',
          branches: [{ when: 'No', then: '“Standby”, with the reason; nothing is transmitted.', tone: 'warn' }],
          yes: 'Well formed',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Still right in spoken radio form?',
          detail: 'Checked again once it is turned into the words an ICAO controller would say.',
          branches: [{ when: 'No', then: '“Standby”, with the reason; nothing is transmitted.', tone: 'warn' }],
          yes: 'Cleared to be spoken',
        },
        { actor: 'store', label: 'The controller remembers what it said', detail: 'Every message that passes is recorded in the controller’s memory.' },
        { actor: 'app', label: 'The answer is spoken', goto: 'voice' },
      ],
      outputs: ['A checked answer', 'Or “standby”, with the reason'],
      feeds: ['voice'],
    },
    {
      id: 'readback',
      title: 'Readback',
      trigger: 'When you repeat an instruction back',
      summary: 'Your readback, repeating the instruction to confirm it, is compared with what the controller said, item by item.',
      steps: [
        { actor: 'you', label: 'Read the instruction back', detail: 'Spoken or typed, like any other call.' },
        { actor: 'app', label: 'Which items need a readback?', detail: 'Runway, altitude, squawk and hold-short instructions (the order to stop before a runway).' },
        { actor: 'app', label: 'Spoken digits become numbers', detail: 'If you correct yourself, your last value counts.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is every item right?',
          branches: [
            { when: 'An item is wrong', then: 'The controller restates it.', tone: 'bad' },
            { when: 'An item is missing', then: 'The controller names what you left out.', tone: 'warn' },
          ],
          yes: '“Readback correct”',
        },
        { actor: 'app', label: 'The reply is spoken', goto: 'voice' },
      ],
      outputs: ['“Readback correct”', 'Or the item restated'],
      feeds: ['voice'],
    },
    {
      id: 'voice',
      title: 'Voice',
      trigger: 'Whenever a controller or another aircraft speaks',
      summary: 'The answer becomes a radio voice through local text-to-speech.',
      steps: [
        { actor: 'app', label: 'ICAO pronunciation', detail: 'Numbers are said the radio way, such as “tree” for three and “niner” for nine.' },
        { actor: 'ai', label: 'Local text-to-speech', detail: 'Each controller at each airport has a voice of its own; other aircraft get voices by the language of their airline.' },
        { actor: 'app', label: 'Make it sound like a radio', detail: 'The narrow sound of a radio, with static and clicks.' },
        { actor: 'app', label: 'Level the loudness', detail: 'Every voice plays at the same volume.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Where are you listening?',
          branches: [
            { when: 'In the web portal', then: 'Played in the portal.' },
            { when: 'In X-Plane', then: 'Played on COM1, the simulator’s main radio.' },
          ],
        },
      ],
      outputs: ['The controller’s voice, on the radio'],
    },
    {
      id: 'traffic',
      title: 'Traffic and supervisor',
      trigger: 'Every second while you fly',
      summary: 'Other aircraft are spaced by the ICAO rules, and a supervisor watches your flight for safety problems.',
      steps: [
        { actor: 'app', label: 'Sort aircraft by wake', detail: 'Super, Heavy, Medium or Light: bigger aircraft leave stronger turbulence behind them.' },
        { actor: 'app', label: 'Space the arrivals', detail: 'When airport traffic is added, arrivals are spaced 3 to 8 nautical miles apart, from the ICAO table.' },
        { actor: 'app', label: 'Space the departures', detail: 'At least 2 minutes apart, 3 minutes behind a Super.' },
        { actor: 'app', label: 'Traffic at cruise', detail: 'Above 10,000 ft, up to 8 cruising aircraft fly real airline routes.' },
        { kind: 'schedule', actor: 'app', label: 'The supervisor checks every second' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Anything unsafe?',
          branches: [
            { when: 'Closer than 3 nm and 1,000 ft to another aircraft', then: 'Separation warning.', tone: 'bad' },
            { when: 'On a runway without clearance', then: 'Runway incursion warning.', tone: 'bad' },
            { when: 'Over 250 kt below 10,000 ft', then: 'Speed warning.', tone: 'warn' },
            { when: 'Off your cleared altitude', then: 'Altitude warning.', tone: 'warn' },
            { when: 'An unstable approach, or slow to leave the runway', then: 'Spoken warning.', tone: 'warn' },
            { when: 'A go-around is needed', then: 'Go-around warning.', tone: 'bad' },
          ],
          yes: 'All normal',
        },
        { kind: 'loop', actor: 'app', label: 'Spoken warnings, never repeated too soon', detail: 'The same issue is not called again for 30 seconds, with at least 3 seconds between calls.', goto: 'voice' },
      ],
      outputs: ['Spaced arrivals and departures', 'Cruise traffic', 'Spoken safety warnings'],
      feeds: ['voice'],
    },
    {
      id: 'plan',
      title: 'Plan the flight',
      trigger: 'Before and during your flight',
      summary: 'Your flight plan sets the scene: runway, procedures, the clearance request and a checklist that follows you.',
      steps: [
        { actor: 'you', label: 'Load your flight plan', detail: 'Import it from SimBrief (the flight-planning service), upload a file, or pick a saved flight.' },
        { actor: 'store', label: 'Runway and procedures', detail: 'Taken from the navigation data.' },
        { actor: 'you', label: 'File the plan', detail: 'Your clearance request is sent.', goto: 'decide' },
        { actor: 'app', label: 'The checklist ticks itself', detail: '11 IFR steps of flight progress; most tick themselves from your aircraft’s state, and you tick ATIS and clearance.' },
        { actor: 'app', label: 'Suggested next call', detail: 'With a hint when COM1 is tuned to the wrong station.' },
        {
          kind: 'schedule',
          actor: 'app',
          label: 'ATIS read out when you tune it',
          detail: 'ATIS is the airport’s recorded information broadcast. Checked every 5 seconds, then not repeated for 60 seconds.',
          goto: 'voice',
        },
        { actor: 'store', label: 'Navigation data, imported once', detail: 'Airports, navaids (radio beacons), fixes and procedures on first start; an airport’s taxiways the first time you use it.' },
      ],
      outputs: ['Runway and procedures', 'Clearance request', 'A live checklist', 'ATIS'],
      feeds: ['decide', 'voice'],
    },
  ],
};

const ro: WorkflowSet = {
  intro:
    'AI_ATC rulează nouă fluxuri alături de X-Plane. Avionul tău e urmărit în fiecare secundă; apelurile radio sunt înțelese de AI-ul local, dar fiecare răspuns e construit din reguli și date de navigație și verificat înainte să fie rostit. Alege unul ca să-l urmărești pas cu pas.',
  workflows: [
    {
      id: 'link',
      title: 'Legătura cu simulatorul',
      trigger: 'La fiecare cadru în X-Plane; trimis în fiecare secundă',
      summary: 'Un plugin din X-Plane citește avionul, așa că controlorul știe mereu unde ești și ce faci.',
      steps: [
        { actor: 'sim', label: 'Citește avionul, la fiecare cadru', detail: 'Poziție, viteze, direcții, radiouri, vreme, tren de aterizare și flapsuri.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'În ce fază a zborului ești?',
          detail: 'Decisă de reguli fixe, nu de AI.',
          branches: [
            { when: 'Sub 5 kt', then: 'Parcat.' },
            { when: 'Sub 30 kt', then: 'Rulaj.' },
            { when: 'Accelerezi pentru decolare', then: 'Rulaj de decolare.' },
            { when: 'Sub 1.500 ft, în urcare', then: 'Plecare.' },
            { when: 'Sub 3.000 ft, în coborâre, cu trenul scos', then: 'Apropiere.' },
            { when: 'Urci sau cobori cu peste 500 ft pe minut', then: 'Urcare sau coborâre.' },
          ],
          yes: 'Altfel: croazieră',
        },
        { kind: 'schedule', actor: 'sim', label: 'Schimb de date cu controlorul', detail: 'Starea avionului e trimisă în fiecare secundă, traficul din jur e citit la fiecare jumătate de secundă, iar comenzile controlorului sunt preluate în fiecare secundă.' },
        { kind: 'schedule', actor: 'ext', label: 'Adaugă vremea reală', detail: 'La fiecare 5 minute se adaugă un METAR real (buletinul meteo oficial al aeroportului).' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Vești de la simulator în 30 de secunde?',
          branches: [{ when: 'Nu', then: 'Marcat ca deconectat.', tone: 'warn' }],
          yes: 'Conectat',
        },
        { actor: 'app', label: 'Controlorul îți cunoaște poziția', goto: 'understand' },
      ],
      outputs: ['Poziția, viteza și faza zborului', 'Vremea în timp real'],
      feeds: ['understand', 'traffic', 'plan'],
    },
    {
      id: 'speak',
      title: 'Vorbești',
      trigger: 'Când ții apăsat butonul de emisie',
      summary: 'Apelul tău radio e înregistrat și transformat în text de recunoașterea vocală locală.',
      steps: [
        { actor: 'you', label: 'Ții apăsat butonul de emisie', detail: 'Push-to-talk, în portalul web sau direct în simulator.' },
        { actor: 'app', label: 'Apelul e înregistrat', detail: 'Înregistrat la 16 kHz cât timp ții butonul.' },
        { actor: 'ai', label: 'Vocea devine text', detail: 'Recunoașterea vocală locală (Whisper) scrie ce ai spus.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'S-a spus ceva?',
          branches: [{ when: 'Nu', then: 'Vezi mesajul „No speech detected” (nu s-a detectat vorbire).', tone: 'warn' }],
          yes: 'Textul apelului',
        },
        { actor: 'you', label: 'Sau îl scrii', detail: 'Poți scrie apelul în loc să-l rostești.' },
        { actor: 'app', label: 'Cuvintele ajung la controlor', goto: 'understand' },
      ],
      outputs: ['Textul apelului tău radio'],
      feeds: ['understand'],
    },
    {
      id: 'understand',
      title: 'Înțelegerea cererii',
      trigger: 'După fiecare apel al tău',
      summary: 'AI-ul local doar încadrează ce ai spus într-unul din 14 tipuri de cereri; nu scrie niciodată răspunsul.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Se cunosc poziția și aeroportul tău?',
          branches: [{ when: 'Nu', then: '„Standby” (așteaptă), cu motivul.', tone: 'warn' }],
          yes: 'Cunoscute',
        },
        {
          actor: 'ai',
          label: 'Încadrează apelul într-unul din 14 tipuri',
          detail: 'AI-ul local alege doar tipul, reglat să dea același răspuns pentru aceleași cuvinte, cu o limită de 20 de secunde.',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Regulile de cuvinte au ultimul cuvânt',
          branches: [
            { when: 'Ai spus „mayday”', then: 'Tratat ca urgență.', tone: 'warn' },
            { when: 'Ai repetat o instrucțiune', then: 'Tratat ca readback (confirmare prin repetare).', goto: 'readback' },
            { when: '„Say again” sau o schimbare de nivel', then: 'Recunoscute după cuvintele în sine.' },
          ],
          yes: 'Altfel rămâne alegerea AI-ului',
        },
        { actor: 'app', label: 'Citește indicativul tău', detail: 'Luat din cuvintele tale, niciodată inventat.' },
        { actor: 'app', label: 'Cererea merge mai departe', goto: 'decide' },
      ],
      outputs: ['Unul din 14 tipuri de cereri', 'Indicativul tău'],
      feeds: ['decide', 'readback'],
    },
    {
      id: 'decide',
      title: 'Decizia răspunsului',
      trigger: 'Pentru fiecare cerere înțeleasă',
      summary: 'Regulile și datele de navigație construiesc răspunsul controlorului; niciun text nu e scris de AI.',
      steps: [
        { actor: 'app', label: 'Alege pista în folosință', detail: 'Întâi regulile de flux ale aeroportului; altfel decide vântul.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ce permite vântul?',
          branches: [
            { when: 'Vânt din spate peste 10 kt', then: 'Pista e exclusă.', tone: 'bad' },
            { when: 'Calm, sub 3 kt', then: 'Cea mai lungă pistă.' },
          ],
          yes: 'Altfel: pista cu cel mai mult vânt din față',
        },
        { actor: 'app', label: 'Pista rămâne stabilă', detail: 'O pistă rămâne în folosință cel puțin 10 minute și se schimbă doar pentru 3 kt în plus de vânt din față.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ești pe frecvența corectă?',
          branches: [{ when: 'Diferență de peste 0,012 MHz', then: '„Wrong frequency” (frecvență greșită).', tone: 'bad' }],
          yes: 'Frecvența corectă',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ce ai cerut?',
          branches: [
            { when: 'Rulaj', then: 'Un traseu pe căile de rulare ale aeroportului până la punctul de așteptare dinaintea pistei.' },
            { when: 'Autorizare IFR', then: 'Pentru zborul instrumental: procedura de plecare (SID, ruta publicată de ieșire) luată din ruta ta, un squawk (codul transponderului) și frecvența de plecare.' },
            { when: 'Decolare', then: 'Doar după intervalul de turbulență de siaj lăsată de ultima plecare.' },
            { when: 'Aterizare', then: 'Numărul tău în secvență, traficul din față și vântul.' },
            { when: 'Apropiere', then: 'Cea mai bună apropiere publicată: întâi ILS (sistemul de aterizare instrumentală), apoi GLS, apoi LOC.' },
            { when: 'Coborâre', then: 'Niciodată sub prima altitudine a apropierii.' },
          ],
        },
        { actor: 'store', label: 'Fiecare detaliu, din datele de navigație', detail: 'Pistele, căile de rulare, procedurile și frecvențele vin din datele reale ale aeroportului.' },
        { actor: 'app', label: 'Răspunsul trece la verificări', goto: 'check' },
      ],
      outputs: ['Pista în folosință', 'Traseu de rulaj, autorizare sau secvență de aterizare', 'Un răspuns construit din reguli'],
      feeds: ['check'],
    },
    {
      id: 'check',
      title: 'Verificarea înainte de emisie',
      trigger: 'Înainte să se rostească ceva',
      summary: 'Trei verificări filtrează fiecare răspuns; dacă una eșuează, auzi „standby” cu motivul și nu se transmite nimic.',
      steps: [
        {
          kind: 'decision',
          actor: 'store',
          label: 'Există totul la acel aeroport?',
          detail: 'Fiecare pistă, cale de rulare, procedură, punct de navigație (fix) și frecvență.',
          branches: [{ when: 'Nu', then: '„Standby”, cu motivul; nu se transmite nimic.', tone: 'warn' }],
          yes: 'Toate reale',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Mesajul e corect alcătuit?',
          detail: 'Indicativul tău; altitudine 100–60.000 ft, în sute; direcție 1–360; viteză 60–400 kt; un squawk valid.',
          branches: [{ when: 'Nu', then: '„Standby”, cu motivul; nu se transmite nimic.', tone: 'warn' }],
          yes: 'Corect alcătuit',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Tot corect în forma rostită?',
          detail: 'Verificat din nou după ce e transformat în frazeologia ICAO pe care ar folosi-o un controlor.',
          branches: [{ when: 'Nu', then: '„Standby”, cu motivul; nu se transmite nimic.', tone: 'warn' }],
          yes: 'Gata de rostit',
        },
        { actor: 'store', label: 'Controlorul ține minte ce a spus', detail: 'Fiecare mesaj care trece e păstrat în memoria controlorului.' },
        { actor: 'app', label: 'Răspunsul e rostit', goto: 'voice' },
      ],
      outputs: ['Un răspuns verificat', 'Sau „standby”, cu motivul'],
      feeds: ['voice'],
    },
    {
      id: 'readback',
      title: 'Readback',
      trigger: 'Când repeți o instrucțiune',
      summary: 'Readback-ul tău, adică repetarea instrucțiunii ca s-o confirmi, e comparat punct cu punct cu ce a spus controlorul.',
      steps: [
        { actor: 'you', label: 'Repeți instrucțiunea', detail: 'Rostită sau scrisă, ca orice alt apel.' },
        { actor: 'app', label: 'Ce trebuie repetat?', detail: 'Pista, altitudinea, squawk-ul și instrucțiunile hold-short (oprirea înaintea unei piste).' },
        { actor: 'app', label: 'Cifrele rostite devin numere', detail: 'Dacă te corectezi, contează ultima valoare spusă.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'E corect fiecare punct?',
          branches: [
            { when: 'Un punct e greșit', then: 'Controlorul îl repetă corect.', tone: 'bad' },
            { when: 'Un punct lipsește', then: 'Controlorul spune ce ai omis.', tone: 'warn' },
          ],
          yes: '„Readback correct”',
        },
        { actor: 'app', label: 'Răspunsul e rostit', goto: 'voice' },
      ],
      outputs: ['„Readback correct”', 'Sau punctul repetat corect'],
      feeds: ['voice'],
    },
    {
      id: 'voice',
      title: 'Vocea',
      trigger: 'Oricând vorbește un controlor sau alt avion',
      summary: 'Răspunsul devine o voce radio prin sinteza vocală locală.',
      steps: [
        { actor: 'app', label: 'Pronunție ICAO', detail: 'Numerele sunt rostite ca în radio: „tree” pentru trei, „niner” pentru nouă.' },
        { actor: 'ai', label: 'Sinteză vocală locală', detail: 'Fiecare controlor de la fiecare aeroport are vocea lui; celelalte avioane primesc voci după limba companiei lor.' },
        { actor: 'app', label: 'Sună ca un radio', detail: 'Sunetul îngust al stației radio, cu paraziți și clicuri.' },
        { actor: 'app', label: 'Volum egalizat', detail: 'Toate vocile se aud la același volum.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Unde asculți?',
          branches: [
            { when: 'În portalul web', then: 'Redat în portal.' },
            { when: 'În X-Plane', then: 'Redat pe COM1, radioul principal din simulator.' },
          ],
        },
      ],
      outputs: ['Vocea controlorului, în stație'],
    },
    {
      id: 'traffic',
      title: 'Trafic și supervizor',
      trigger: 'În fiecare secundă de zbor',
      summary: 'Celelalte avioane sunt separate după regulile ICAO, iar un supervizor îți urmărește zborul pentru probleme de siguranță.',
      steps: [
        { actor: 'app', label: 'Avioanele, pe categorii de siaj', detail: 'Super, Heavy, Medium sau Light: avioanele mari lasă în urmă turbulență mai puternică.' },
        { actor: 'app', label: 'Separă sosirile', detail: 'Când se adaugă trafic la aeroport, sosirile sunt la 3–8 mile nautice una de alta, după tabelul ICAO.' },
        { actor: 'app', label: 'Separă plecările', detail: 'La cel puțin 2 minute, 3 minute în spatele unui Super.' },
        { actor: 'app', label: 'Trafic în croazieră', detail: 'Peste 10.000 ft, până la 8 avioane zboară pe rute reale ale companiilor aeriene.' },
        { kind: 'schedule', actor: 'app', label: 'Supervizorul verifică în fiecare secundă' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ceva nesigur?',
          branches: [
            { when: 'Mai aproape de 3 nm și 1.000 ft de alt avion', then: 'Avertizare de separare.', tone: 'bad' },
            { when: 'Pe pistă fără autorizare', then: 'Avertizare de incursiune pe pistă.', tone: 'bad' },
            { when: 'Peste 250 kt sub 10.000 ft', then: 'Avertizare de viteză.', tone: 'warn' },
            { when: 'Abatere de la altitudinea autorizată', then: 'Avertizare de altitudine.', tone: 'warn' },
            { when: 'Apropiere instabilă sau eliberezi pista prea încet', then: 'Avertizare rostită.', tone: 'warn' },
            { when: 'E nevoie de o ratare (go-around)', then: 'Avertizare de ratare.', tone: 'bad' },
          ],
          yes: 'Totul normal',
        },
        { kind: 'loop', actor: 'app', label: 'Avertizări rostite, fără repetări dese', detail: 'Aceeași problemă nu e anunțată din nou 30 de secunde, cu cel puțin 3 secunde între apeluri.', goto: 'voice' },
      ],
      outputs: ['Sosiri și plecări separate', 'Trafic în croazieră', 'Avertizări de siguranță rostite'],
      feeds: ['voice'],
    },
    {
      id: 'plan',
      title: 'Planificarea zborului',
      trigger: 'Înainte și în timpul zborului',
      summary: 'Planul de zbor pregătește totul: pista, procedurile, cererea de autorizare și o listă de verificare care te urmează.',
      steps: [
        { actor: 'you', label: 'Încarci planul de zbor', detail: 'Îl imporți din SimBrief (serviciul de planificare a zborului), încarci un fișier sau alegi un zbor salvat.' },
        { actor: 'store', label: 'Pista și procedurile', detail: 'Luate din datele de navigație.' },
        { actor: 'you', label: 'Depui planul', detail: 'Cererea ta de autorizare e trimisă.', goto: 'decide' },
        { actor: 'app', label: 'Lista de verificare se bifează singură', detail: '11 etape IFR ale zborului; cele mai multe se bifează din starea avionului, iar ATIS-ul și autorizarea le bifezi tu.' },
        { actor: 'app', label: 'Următorul apel sugerat', detail: 'Cu un indiciu când COM1 e pe stația greșită.' },
        {
          kind: 'schedule',
          actor: 'app',
          label: 'ATIS citit când îl acordezi',
          detail: 'ATIS e buletinul de informații înregistrat al aeroportului. Verificat la fiecare 5 secunde, apoi nerepetat timp de 60 de secunde.',
          goto: 'voice',
        },
        { actor: 'store', label: 'Datele de navigație, importate o dată', detail: 'Aeroporturile, radiofarurile, punctele de navigație și procedurile la prima pornire; căile de rulare ale unui aeroport, prima dată când îl folosești.' },
      ],
      outputs: ['Pista și procedurile', 'Cererea de autorizare', 'O listă de verificare vie', 'ATIS'],
      feeds: ['decide', 'voice'],
    },
  ],
};

export default { en, ro };
