// ATHENA's workflows, traced from its source code (numbers are the code's defaults).
import type { WorkflowSet } from './types';

const en: WorkflowSet = {
  intro:
    'ATHENA runs eight workflows. Most start when you act: open a case, add a subject, press Run or ask a question; indexing and notifications work in the background. Pick one to follow it step by step.',
  workflows: [
    {
      id: 'case',
      title: 'Open a case',
      trigger: 'When you start a new investigation',
      summary: 'A case holds one investigation: its subjects, findings, tasks and team.',
      steps: [
        {
          kind: 'decision',
          actor: 'you',
          label: 'Blank, or from a template?',
          branches: [{ when: 'Template', then: 'One of 5: Person, Domain, Email, Organization or Incident. Its task checklist is copied into the case.' }],
          yes: 'Blank case',
        },
        { actor: 'app', label: 'Give the case its number', detail: 'ATH, then the year, then a four-digit number.' },
        { actor: 'app', label: 'You become the Owner', detail: 'Members and teams can join as Owner, Member or Viewer.' },
        { actor: 'store', label: 'Recorded in the audit log', detail: 'Case creation is one of the key actions the log keeps.' },
        { actor: 'you', label: 'Work through the tasks', detail: 'Each task moves from pending to in progress to done; the case shows its progress as a percentage.', goto: 'subjects' },
      ],
      outputs: ['A numbered case', 'A task checklist with progress'],
      feeds: ['subjects'],
    },
    {
      id: 'subjects',
      title: 'Add subjects',
      trigger: 'When you add someone or something to a case',
      summary: 'The people and things under investigation, what identifies them and how they are connected.',
      steps: [
        { actor: 'you', label: 'Add a subject', detail: 'A person, organisation, place, device or online identity.' },
        {
          actor: 'you',
          label: 'Attach its identifiers',
          detail: 'Username, email, phone, name, web address, image, IP address, domain, crypto wallet or social profile link.',
        },
        { actor: 'you', label: 'Link subjects together', detail: 'Each relationship has a type and a confidence.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Linked to itself?',
          branches: [{ when: 'Yes', then: 'Refused: a subject cannot be related to itself.', tone: 'bad' }],
          yes: 'Relationship saved',
        },
        { actor: 'app', label: 'Draw the network graph', detail: 'Subjects and their links on one interactive picture.' },
        { actor: 'store', label: 'Identifiers ready to collect on', goto: 'collect' },
      ],
      outputs: ['Subjects with their identifiers', 'A network graph of relationships'],
      feeds: ['collect'],
    },
    {
      id: 'collect',
      title: 'Collect',
      trigger: 'When you press Run on an identifier, or Run all',
      summary: 'Each identifier goes to the collectors that fit it, and every result comes back as a finding for you to review.',
      steps: [
        { actor: 'app', label: 'Queue the run', detail: 'A background worker picks it up: 30-second limit, up to 50 results.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Which collectors fit the identifier?',
          branches: [
            { when: 'Web search', then: 'A self-hosted search engine, with a query shaped for each type of identifier.' },
            { when: 'DNS & WHOIS', then: 'Name-server and registration records.' },
            { when: 'Breach check', then: 'An outside breach service is asked about it.' },
            { when: 'Reverse image', then: 'Yandex image search, with Bing as a fallback.' },
          ],
          yes: 'Social identifiers',
        },
        {
          actor: 'ext',
          label: 'Search the social platforms',
          detail: 'A quick profile check on 15 sites, or a deep search of 52 platforms, 5 at a time and politely paced. Pages that only say “not found” are recognised.',
        },
        { actor: 'ai', label: 'Read the posts', detail: 'Up to 30 posts; the local AI writes a behavioural profile from them.' },
        { kind: 'loop', actor: 'app', label: 'If a run crashes', detail: 'It is retried twice, 30 seconds apart. A search that comes back with errors is recorded as a failed run.' },
        { actor: 'store', label: 'Each result saved as a pending finding', detail: 'The run history updates live on screen.', goto: 'review' },
        { actor: 'app', label: 'Your team is notified' },
        {
          kind: 'loop',
          actor: 'app',
          label: 'Search deeper',
          detail: 'Emails, usernames, links, IP addresses and phone numbers are pulled out of a finding. Anything searched in the last hour is skipped; the rest go to the collectors that fit.',
        },
      ],
      outputs: ['Pending findings', 'A live run history'],
      feeds: ['review', 'index'],
    },
    {
      id: 'review',
      title: 'Review findings',
      trigger: 'Whenever findings are waiting',
      summary: 'You decide which findings count as evidence; rejected ones never reach a report.',
      steps: [
        {
          actor: 'app',
          label: 'Each finding arrives with a confidence',
          detail: 'Set by the collector that found it: a DNS record gets 0.95; a web result starts at 0.3 and rises with each match.',
        },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Confirm or reject?',
          branches: [{ when: 'Reject', then: 'Marked rejected, with your notes. It never reaches a report.', tone: 'bad' }],
          yes: 'Confirmed, with your notes',
        },
        { actor: 'store', label: 'Recorded in the audit log', detail: 'Every evidence decision is logged.' },
        { actor: 'app', label: 'Your team is notified' },
        {
          actor: 'app',
          label: 'Sources build a track record',
          detail: 'Each source’s share of confirmed findings. Once 3 or more of its findings are reviewed, the record goes to the AI with the evidence.',
          goto: 'assistant',
        },
        { actor: 'store', label: 'Confirmed findings are ready for the report', goto: 'report' },
      ],
      outputs: ['Findings you have confirmed', 'An audit trail of your decisions'],
      feeds: ['report', 'assistant'],
    },
    {
      id: 'index',
      title: 'Index and search',
      trigger: 'Every time a finding is saved',
      summary: 'Saved text is turned into a meaning vector, so your cases can be searched by meaning as well as by words.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Has the text changed?',
          branches: [{ when: 'No', then: 'Skipped; nothing to redo.' }],
          yes: 'New or changed text',
        },
        { actor: 'ai', label: 'Turn the text into a meaning vector', detail: 'Done by the local AI.' },
        { actor: 'store', label: 'Stored in the search index' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'How do you search?',
          branches: [
            { when: 'By meaning', then: 'Results with a similarity of 0.5 or more.' },
            { when: 'Hybrid', then: 'Words and meaning together; a result found by both ranks higher.', tone: 'ok' },
          ],
        },
        { actor: 'you', label: 'Search across all your cases', detail: 'Your last 20 searches are kept, and you can save the ones you reuse.', goto: 'assistant' },
      ],
      outputs: ['Search by meaning or hybrid', 'Search history and saved searches'],
      feeds: ['assistant'],
    },
    {
      id: 'assistant',
      title: 'Ask the assistant',
      trigger: 'When you ask a question on a case',
      summary: 'The local AI answers from the case’s own findings, and can draft a report that you then review.',
      steps: [
        { actor: 'you', label: 'Ask a question' },
        { actor: 'app', label: 'Put it in the queue' },
        {
          actor: 'store',
          label: 'Gather the context',
          detail: 'The 5 most relevant findings, your custom instructions, your recent actions on the case and the last 10 messages.',
        },
        { actor: 'store', label: 'Add your best answers as examples', detail: 'Answers you rated 👍 show the model what you want.' },
        { actor: 'ai', label: 'The local AI answers', detail: 'Set for sober, consistent answers (temperature 0.3).' },
        { kind: 'schedule', actor: 'app', label: 'The page checks for the answer', detail: 'Every 2.5 seconds.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Did the model answer?',
          branches: [{ when: 'No', then: 'A visible failure message, never silence.', tone: 'warn' }],
          yes: 'Answer shown',
        },
        {
          actor: 'ai',
          label: 'Or ask for a free-form AI report',
          detail: 'Written from every finding that was not rejected, with each source’s track record. Saved as a finding marked “needs review”, so it goes through your review like any other.',
          goto: 'review',
        },
      ],
      outputs: ['Answers grounded in the case', 'AI reports to review'],
      feeds: ['review'],
    },
    {
      id: 'report',
      title: 'Report and export',
      trigger: 'When you generate a report or export a case',
      summary: 'A structured report written from the case’s findings, plus exports that carry the whole case to other tools.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Profile set by the most common subject type',
          branches: [
            { when: 'Person', then: 'Person profile, with no infrastructure section.' },
            { when: 'Organisation', then: 'Organisation profile.' },
            { when: 'Infrastructure', then: 'Infrastructure profile.' },
            { when: 'Anything else', then: 'General profile.' },
          ],
        },
        { actor: 'app', label: 'Sort the findings by source', detail: 'Rejected findings are left out; the sections are built from the rest.' },
        {
          actor: 'ai',
          label: 'The local AI writes 7 parts',
          detail: 'Summary, background, risk, assessment, key findings, recommendations and conclusion. Where a part lacks evidence, it says so.',
        },
        { actor: 'app', label: 'Tidy the sections', detail: 'Empty sections are dropped; up to 15 remain, in a standard order.' },
        { actor: 'app', label: 'Produce the PDF', detail: 'Your team is notified, and the download is recorded in the audit log.' },
        { actor: 'you', label: 'Export the case', detail: 'The whole case as a ZIP file, or in the STIX 2.1 exchange format.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Importing: do both ends of a link exist?',
          detail: 'You can import CSV, JSON or STIX files.',
          branches: [{ when: 'No', then: 'That relationship is skipped.', tone: 'warn' }],
          yes: 'Relationship imported',
        },
      ],
      outputs: ['PDF report', 'ZIP of the whole case', 'STIX 2.1 export'],
    },
    {
      id: 'privacy',
      title: 'Privacy and alerts',
      trigger: 'Set up once in settings; runs in the background',
      summary: 'Optional VPN routing, encrypted secrets, your choice of AI model, and live notifications to you and your other systems.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is the VPN switched on?',
          branches: [{ when: 'Off', then: 'Web requests go out directly.' }],
          yes: 'On: web requests go through the tunnel',
        },
        { kind: 'schedule', actor: 'app', label: 'Status badge in the header', detail: 'Shows the exit IP address and country, checked every 30 seconds.' },
        { actor: 'store', label: 'Secrets stored encrypted', detail: 'VPN profiles and saved login cookies.' },
        { actor: 'you', label: 'Choose the AI model', detail: 'In settings.' },
        { actor: 'app', label: 'Real-time notifications', detail: 'The live connection reconnects by itself; as a backup, the page checks every 30 seconds.' },
        {
          kind: 'loop',
          actor: 'ext',
          label: 'Signed webhooks',
          detail: 'A failed delivery is retried 3 times, after 30, 60 and 120 seconds. After 10 failures the webhook is paused.',
        },
        { actor: 'store', label: 'Key actions in the audit log', detail: 'Case creation, evidence decisions, report downloads and admin changes.' },
      ],
      outputs: ['VPN status badge', 'Live notifications', 'Signed webhooks'],
    },
  ],
};

const ro: WorkflowSet = {
  intro:
    'ATHENA rulează opt fluxuri. Cele mai multe pornesc când acționezi tu: deschizi un caz, adaugi un subiect, apeși Rulează sau pui o întrebare; indexarea și notificările lucrează în fundal. Alege unul ca să-l urmărești pas cu pas.',
  workflows: [
    {
      id: 'case',
      title: 'Deschiderea unui caz',
      trigger: 'Când începi o investigație nouă',
      summary: 'Un caz cuprinde o investigație: subiectele, constatările, sarcinile și echipa ei.',
      steps: [
        {
          kind: 'decision',
          actor: 'you',
          label: 'Gol sau dintr-un șablon?',
          branches: [{ when: 'Șablon', then: 'Unul din 5: Persoană, Domeniu, E-mail, Organizație sau Incident. Lista lui de sarcini e copiată în caz.' }],
          yes: 'Caz gol',
        },
        { actor: 'app', label: 'Cazul primește un număr', detail: 'ATH, apoi anul, apoi un număr din patru cifre.' },
        { actor: 'app', label: 'Devii Proprietar', detail: 'Membrii și echipele pot intra ca Proprietar, Membru sau Observator.' },
        { actor: 'store', label: 'Înregistrat în jurnalul de audit', detail: 'Crearea cazului e una dintre acțiunile-cheie păstrate în jurnal.' },
        { actor: 'you', label: 'Lucrezi pe sarcini', detail: 'Fiecare sarcină trece din „în așteptare” în „în lucru” și apoi în „gata”; cazul își arată progresul în procente.', goto: 'subjects' },
      ],
      outputs: ['Un caz numerotat', 'O listă de sarcini cu progres'],
      feeds: ['subjects'],
    },
    {
      id: 'subjects',
      title: 'Adăugarea subiecților',
      trigger: 'Când adaugi pe cineva sau ceva într-un caz',
      summary: 'Oamenii și lucrurile investigate, ce îi identifică și cum sunt legați între ei.',
      steps: [
        { actor: 'you', label: 'Adaugi un subiect', detail: 'O persoană, o organizație, un loc, un dispozitiv sau o identitate online.' },
        {
          actor: 'you',
          label: 'Atașezi identificatorii',
          detail: 'Nume de utilizator, e-mail, telefon, nume, adresă web, imagine, adresă IP, domeniu, portofel cripto sau link de profil social.',
        },
        { actor: 'you', label: 'Legi subiecții între ei', detail: 'Fiecare relație are un tip și un grad de încredere.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Legat de el însuși?',
          branches: [{ when: 'Da', then: 'Refuzat: un subiect nu poate fi în relație cu el însuși.', tone: 'bad' }],
          yes: 'Relație salvată',
        },
        { actor: 'app', label: 'Se desenează graficul rețelei', detail: 'Subiecții și legăturile lor, într-o singură imagine interactivă.' },
        { actor: 'store', label: 'Identificatori gata de colectare', goto: 'collect' },
      ],
      outputs: ['Subiecți cu identificatorii lor', 'Un grafic al relațiilor'],
      feeds: ['collect'],
    },
    {
      id: 'collect',
      title: 'Colectarea',
      trigger: 'Când apeși Rulează pe un identificator sau Rulează tot',
      summary: 'Fiecare identificator ajunge la colectorii potriviți, iar fiecare rezultat revine ca o constatare pe care o verifici tu.',
      steps: [
        { actor: 'app', label: 'Rularea intră în coadă', detail: 'O preia un proces din fundal: limită de 30 de secunde, maximum 50 de rezultate.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ce colectori se potrivesc identificatorului?',
          branches: [
            { when: 'Căutare web', then: 'Un motor de căutare găzduit de tine, cu o interogare adaptată fiecărui tip de identificator.' },
            { when: 'DNS și WHOIS', then: 'Înregistrările DNS și datele de înregistrare ale domeniului.' },
            { when: 'Verificare de breșe', then: 'E întrebat un serviciu extern de breșe de date.' },
            { when: 'Căutare inversă de imagini', then: 'Căutarea de imagini Yandex, cu Bing ca rezervă.' },
          ],
          yes: 'Identificatori sociali',
        },
        {
          actor: 'ext',
          label: 'Caută pe platformele sociale',
          detail: 'O verificare rapidă de profil pe 15 site-uri sau o căutare amănunțită pe 52 de platforme, câte 5 odată și în ritm politicos. Paginile care spun doar „nu există” sunt recunoscute.',
        },
        { actor: 'ai', label: 'Citește postările', detail: 'Până la 30 de postări; AI-ul local scrie din ele un profil comportamental.' },
        { kind: 'loop', actor: 'app', label: 'Dacă o rulare se blochează', detail: 'E reîncercată de două ori, la 30 de secunde distanță. O căutare care întoarce erori e înregistrată ca rulare eșuată.' },
        { actor: 'store', label: 'Fiecare rezultat, salvat ca constatare în așteptare', detail: 'Istoricul rulărilor se actualizează live pe ecran.', goto: 'review' },
        { actor: 'app', label: 'Echipa ta e anunțată' },
        {
          kind: 'loop',
          actor: 'app',
          label: 'Căutare mai adâncă',
          detail: 'Din constatare se extrag e-mailuri, nume de utilizator, linkuri, adrese IP și numere de telefon. Ce s-a căutat în ultima oră e sărit; restul merge la colectorii potriviți.',
        },
      ],
      outputs: ['Constatări în așteptare', 'Un istoric live al rulărilor'],
      feeds: ['review', 'index'],
    },
    {
      id: 'review',
      title: 'Verificarea constatărilor',
      trigger: 'Oricând există constatări în așteptare',
      summary: 'Tu decizi care constatări devin dovezi; cele respinse nu ajung niciodată într-un raport.',
      steps: [
        {
          actor: 'app',
          label: 'Fiecare constatare vine cu un grad de încredere',
          detail: 'Stabilit de colectorul care a găsit-o: o înregistrare DNS primește 0,95; un rezultat web pornește de la 0,3 și crește cu fiecare potrivire.',
        },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Confirmi sau respingi?',
          branches: [{ when: 'Respingi', then: 'Marcată ca respinsă, cu notele tale. Nu ajunge niciodată într-un raport.', tone: 'bad' }],
          yes: 'Confirmată, cu notele tale',
        },
        { actor: 'store', label: 'Înregistrată în jurnalul de audit', detail: 'Fiecare decizie asupra dovezilor e consemnată.' },
        { actor: 'app', label: 'Echipa ta e anunțată' },
        {
          actor: 'app',
          label: 'Sursele își construiesc un istoric',
          detail: 'Ce parte din constatările fiecărei surse a fost confirmată. După minimum 3 verificări, istoricul ajunge la AI împreună cu dovezile.',
          goto: 'assistant',
        },
        { actor: 'store', label: 'Constatările confirmate, gata pentru raport', goto: 'report' },
      ],
      outputs: ['Constatări confirmate de tine', 'O evidență a deciziilor tale'],
      feeds: ['report', 'assistant'],
    },
    {
      id: 'index',
      title: 'Indexare și căutare',
      trigger: 'De fiecare dată când se salvează o constatare',
      summary: 'Textul salvat e transformat într-un vector de sens, ca să-ți poți căuta cazurile după sens, nu doar după cuvinte.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'S-a schimbat textul?',
          branches: [{ when: 'Nu', then: 'Sărită; nu e nimic de refăcut.' }],
          yes: 'Text nou sau schimbat',
        },
        { actor: 'ai', label: 'Textul devine un vector de sens', detail: 'De către AI-ul local.' },
        { actor: 'store', label: 'Salvat în indexul de căutare' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Cum cauți?',
          branches: [
            { when: 'După sens', then: 'Rezultate cu o asemănare de 0,5 sau mai mult.' },
            { when: 'Hibrid', then: 'Cuvinte și sens împreună; un rezultat găsit de ambele urcă mai sus.', tone: 'ok' },
          ],
        },
        { actor: 'you', label: 'Cauți în toate cazurile tale', detail: 'Ultimele 20 de căutări sunt păstrate și le poți salva pe cele pe care le refolosești.', goto: 'assistant' },
      ],
      outputs: ['Căutare după sens sau hibridă', 'Istoric și căutări salvate'],
      feeds: ['assistant'],
    },
    {
      id: 'assistant',
      title: 'Întrebi asistentul',
      trigger: 'Când pui o întrebare într-un caz',
      summary: 'AI-ul local răspunde din constatările cazului și poate schița un raport pe care îl verifici apoi tu.',
      steps: [
        { actor: 'you', label: 'Pui o întrebare' },
        { actor: 'app', label: 'Întrebarea intră în coadă' },
        {
          actor: 'store',
          label: 'Se adună contextul',
          detail: 'Cele mai relevante 5 constatări, instrucțiunile tale, acțiunile tale recente în caz și ultimele 10 mesaje.',
        },
        { actor: 'store', label: 'Cele mai bune răspunsuri, ca exemple', detail: 'Răspunsurile notate de tine cu 👍 îi arată modelului ce vrei.' },
        { actor: 'ai', label: 'AI-ul local răspunde', detail: 'Reglat pentru răspunsuri sobre și constante (temperatură 0,3).' },
        { kind: 'schedule', actor: 'app', label: 'Pagina verifică dacă a venit răspunsul', detail: 'La fiecare 2,5 secunde.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'A răspuns modelul?',
          branches: [{ when: 'Nu', then: 'Un mesaj de eroare vizibil, niciodată tăcere.', tone: 'warn' }],
          yes: 'Răspuns afișat',
        },
        {
          actor: 'ai',
          label: 'Sau ceri un raport AI liber',
          detail: 'Scris din toate constatările care nu au fost respinse, cu istoricul fiecărei surse. Salvat ca o constatare marcată „necesită verificare”, deci trece prin verificarea ta ca oricare alta.',
          goto: 'review',
        },
      ],
      outputs: ['Răspunsuri bazate pe caz', 'Rapoarte AI de verificat'],
      feeds: ['review'],
    },
    {
      id: 'report',
      title: 'Raport și export',
      trigger: 'Când generezi un raport sau exporți un caz',
      summary: 'Un raport structurat, scris din constatările cazului, plus exporturi care duc tot cazul în alte instrumente.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'Profilul, după cel mai frecvent tip de subiect',
          branches: [
            { when: 'Persoană', then: 'Profil de persoană, fără secțiune de infrastructură.' },
            { when: 'Organizație', then: 'Profil de organizație.' },
            { when: 'Infrastructură', then: 'Profil de infrastructură.' },
            { when: 'Altceva', then: 'Profil general.' },
          ],
        },
        { actor: 'app', label: 'Constatările, ordonate după sursă', detail: 'Cele respinse sunt lăsate deoparte; secțiunile se construiesc din rest.' },
        {
          actor: 'ai',
          label: 'AI-ul local scrie 7 părți',
          detail: 'Rezumat, context, risc, evaluare, constatări principale, recomandări și concluzie. Unde o parte nu are dovezi, o spune.',
        },
        { actor: 'app', label: 'Se ordonează secțiunile', detail: 'Secțiunile goale sunt eliminate; rămân maximum 15, într-o ordine standard.' },
        { actor: 'app', label: 'Se generează PDF-ul', detail: 'Echipa ta e anunțată, iar descărcarea e înregistrată în jurnalul de audit.' },
        { actor: 'you', label: 'Exporți cazul', detail: 'Tot cazul ca fișier ZIP sau în formatul de schimb STIX 2.1.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'La import: există ambele capete ale legăturii?',
          detail: 'Poți importa fișiere CSV, JSON sau STIX.',
          branches: [{ when: 'Nu', then: 'Relația e sărită.', tone: 'warn' }],
          yes: 'Relație importată',
        },
      ],
      outputs: ['Raport PDF', 'ZIP cu tot cazul', 'Export STIX 2.1'],
    },
    {
      id: 'privacy',
      title: 'Confidențialitate și alerte',
      trigger: 'Configurat o dată în setări; rulează în fundal',
      summary: 'Rutare opțională prin VPN, secrete criptate, modelul AI ales de tine și notificări live pentru tine și celelalte sisteme ale tale.',
      steps: [
        {
          kind: 'decision',
          actor: 'app',
          label: 'E pornit VPN-ul?',
          branches: [{ when: 'Oprit', then: 'Cererile web pleacă direct.' }],
          yes: 'Pornit: cererile web trec prin tunel',
        },
        { kind: 'schedule', actor: 'app', label: 'Indicatorul de stare din antet', detail: 'Arată adresa IP de ieșire și țara, verificate la fiecare 30 de secunde.' },
        { actor: 'store', label: 'Secrete păstrate criptat', detail: 'Profilurile VPN și cookie-urile de autentificare salvate.' },
        { actor: 'you', label: 'Alegi modelul AI', detail: 'Din setări.' },
        { actor: 'app', label: 'Notificări în timp real', detail: 'Conexiunea live se reface singură; ca rezervă, pagina verifică la fiecare 30 de secunde.' },
        {
          kind: 'loop',
          actor: 'ext',
          label: 'Webhookuri semnate',
          detail: 'O livrare eșuată e reîncercată de 3 ori, după 30, 60 și 120 de secunde. După 10 eșecuri, webhookul e pus pe pauză.',
        },
        { actor: 'store', label: 'Acțiunile-cheie, în jurnalul de audit', detail: 'Crearea cazurilor, deciziile asupra dovezilor, descărcările de rapoarte și modificările de administrare.' },
      ],
      outputs: ['Indicator de stare VPN', 'Notificări live', 'Webhookuri semnate'],
    },
  ],
};

export default { en, ro };
