// BANKY's workflows, traced from its source code (numbers are the code's defaults).
import type { WorkflowSet } from './types';

const en: WorkflowSet = {
  intro:
    'BANKY runs seven workflows, all on your computer. You start the first four: import a statement, confirm its rows, sort them, attach a receipt. Budgets, goals and insights then read your ledger. Pick one to follow it step by step.',
  workflows: [
    {
      id: 'import',
      title: 'Import a statement',
      trigger: 'When you upload a bank statement',
      summary: 'The statement is turned into rows for you to check: by fixed rules for text PDFs and spreadsheets, and by OCR plus the local AI only for scans.',
      steps: [
        { actor: 'app', label: 'Recognise the file', detail: 'From its content.' },
        {
          kind: 'decision',
          actor: 'store',
          label: 'Imported this file before?',
          branches: [{ when: 'Yes', then: 'Refused, with the date it was first imported.', tone: 'bad' }],
          yes: 'New file',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'What kind of file?',
          branches: [
            {
              when: 'PDF with text',
              then: 'Read by the bank’s layout rules (ING, or a generic reader), no AI. Money in or out comes from the debit and credit columns; with no column header, the amount is left blank with a warning.',
            },
            {
              when: 'Spreadsheet, CSV or HTML',
              then: 'A table reader, no AI: credit minus debit, or the direction from the running balance. A balance that doesn’t add up gives a warning.',
            },
          ],
          yes: 'Scan or image',
        },
        { actor: 'app', label: 'Read the page with OCR', detail: 'At 300 dpi, cleaned and straightened.' },
        { actor: 'ai', label: 'The local AI arranges the text into rows', detail: 'It only arranges what OCR read from the page.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Every number checked against the page',
          detail: 'Each amount must equal a number printed on the page, and each date is checked too.',
          branches: [
            { when: 'Number not on the page', then: 'Left blank, with a warning.', tone: 'warn' },
            { when: 'Minus sign not printed', then: 'Warning.', tone: 'warn' },
            { when: 'A character read below 80% confidence', then: '“Confirm it yourself.”', tone: 'warn' },
          ],
          yes: 'Matches the page',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Could anything be read?',
          branches: [{ when: 'No', then: 'The file is deleted, with a clear message.', tone: 'bad' }],
          yes: 'Rows read',
        },
        {
          kind: 'decision',
          actor: 'store',
          label: 'Already in the ledger?',
          detail: 'Same date, amount and description.',
          branches: [{ when: 'Yes', then: 'Flagged as a possible duplicate, never dropped.', tone: 'warn' }],
          yes: 'New row',
        },
        { actor: 'store', label: 'Rows wait for your review', goto: 'review' },
      ],
      outputs: ['Rows waiting for your review', 'A warning on anything uncertain'],
      feeds: ['review'],
    },
    {
      id: 'review',
      title: 'Review and confirm',
      trigger: 'After every import',
      summary: 'You check each row against the original before anything reaches your ledger.',
      steps: [
        { actor: 'app', label: 'The original, side by side', detail: 'The row you are on is highlighted on the statement.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is the row clean?',
          branches: [{ when: 'Has warnings, or came from a scan', then: 'You check it first, then confirm it with any others you select.', tone: 'warn' }],
          yes: 'Clean: confirmed in one click',
        },
        { actor: 'you', label: 'Work from the keyboard', detail: 'j, k, Enter, e and r.' },
        { actor: 'you', label: 'Edit a row', detail: 'The duplicate check runs again on the new values.' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Confirm or reject?',
          branches: [{ when: 'Reject', then: 'Nothing is written.', tone: 'bad' }],
          yes: 'Confirm',
        },
        { actor: 'store', label: 'Written to the ledger', detail: 'Money out is recorded as an expense.', goto: 'categorise' },
        { actor: 'you', label: 'Or start over', detail: 'Discard the whole import, or convert the statement to Excel, fix it and import it again.' },
      ],
      outputs: ['Confirmed transactions in your ledger'],
      feeds: ['categorise'],
    },
    {
      id: 'categorise',
      title: 'Categorise',
      trigger: 'When you ask',
      summary: 'Your own rules sort what they can; the local AI suggests a category for the rest, only from your list.',
      steps: [
        { actor: 'app', label: 'Your rules first', detail: 'Exact match, contains, or pattern. A rule match is certain.' },
        { actor: 'ai', label: 'The rest go to the local AI', detail: '15 at a time, with your category list as the only allowed answers.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is the category on your list?',
          branches: [{ when: 'Invented', then: 'Dropped.', tone: 'bad' }],
          yes: 'On your list',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'How confident?',
          branches: [
            { when: 'Under 0.50', then: 'No category.', tone: 'bad' },
            { when: '0.50 or more', then: 'Shown as a suggestion.', tone: 'warn' },
            { when: '0.80 or more, in the ledger', then: 'Applied.', tone: 'ok' },
          ],
        },
        { actor: 'you', label: 'Accept the rest in one go', detail: 'The remaining suggestions can be accepted together.' },
        {
          kind: 'loop',
          actor: 'you',
          label: 'Change a category in the ledger: a rule is written',
          detail: 'The new rule uses the bank’s own text for that transaction, so your rules sort it from then on.',
        },
      ],
      outputs: ['Categorised transactions', 'Rules learned from your corrections'],
      feeds: ['budgets', 'insights'],
    },
    {
      id: 'receipts',
      title: 'Receipts',
      trigger: 'When you attach a receipt to a transaction',
      summary: 'The items on a receipt are read, then checked against the page and against the transaction.',
      steps: [
        { actor: 'you', label: 'Attach a photo or PDF', detail: 'To a transaction in your ledger.' },
        { actor: 'app', label: 'Read the receipt with OCR' },
        { actor: 'ai', label: 'The local AI lists the items', detail: 'It arranges what OCR read into item lines.' },
        { actor: 'app', label: 'Check every quantity and price', detail: 'Each one against the page.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Do the items add up to the total?',
          branches: [{ when: 'No', then: 'A sentence says so.', tone: 'warn' }],
          yes: 'Yes',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Does the total equal the transaction?',
          detail: 'Exactly.',
          branches: [{ when: 'No', then: 'A sentence says so.', tone: 'warn' }],
          yes: 'Yes',
        },
        { actor: 'you', label: 'Verify the lines', detail: 'Checking a receipt never moves money.' },
      ],
      outputs: ['An itemised receipt, checked against its transaction'],
    },
    {
      id: 'budgets',
      title: 'Budgets and 50/30/20',
      trigger: 'For each monthly budget you set',
      summary: 'A monthly budget per category, with a warning before you overspend, and the 50/30/20 split of your last full month.',
      steps: [
        { actor: 'you', label: 'Set a monthly budget per top category' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'How much is spent?',
          branches: [
            { when: 'Under 75%', then: 'Fine.', tone: 'ok' },
            { when: '75% or more', then: 'Near the limit.', tone: 'warn' },
            { when: '100% or more', then: 'Over, with a warning.', tone: 'bad' },
          ],
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ahead of the month’s pace?',
          branches: [{ when: 'More than 25 points ahead', then: 'Warning.', tone: 'warn' }],
          yes: 'On pace',
        },
        {
          actor: 'app',
          label: '50/30/20 for the last complete month',
          detail: 'Needs, wants and savings. Savings is exact; needs and wants are shown as ranges while some spending is still uncategorised.',
        },
        { actor: 'app', label: 'Warnings go to your insights', goto: 'insights' },
      ],
      outputs: ['Budget status per category', 'Your 50/30/20 split'],
      feeds: ['insights'],
    },
    {
      id: 'goals',
      title: 'Goals and investments',
      trigger: 'When you set a goal or record a valuation',
      summary: 'Money in your goal accounts fills your goals in priority order, with the monthly amount and the projected date for each.',
      steps: [
        { actor: 'you', label: 'Record an investment’s valuation', detail: 'Units × price, plus cash. The snapshot replaces the account’s balance.' },
        { actor: 'store', label: 'Add up the goal accounts', detail: 'Investments count at their latest valuation.' },
        { actor: 'app', label: 'Fill goals in your priority order' },
        { actor: 'app', label: 'Work out the amount per month', detail: 'What you need to put aside each month to reach each goal by its date.' },
        { actor: 'app', label: 'Project the dates', detail: 'From your typical monthly saving: the median of the last 12 months.' },
        { actor: 'ai', label: 'Optional AI commentary', detail: 'Drafted, verified, critiqued, revised and verified again.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is every number in the facts?',
          branches: [{ when: 'No', then: 'The commentary is rejected. If none passes, you get just the numbers.', tone: 'bad' }],
          yes: 'Commentary shown',
        },
      ],
      outputs: ['Progress on each goal', 'The amount needed per month', 'Projected dates'],
    },
    {
      id: 'insights',
      title: 'Insights and monthly report',
      trigger: 'When you open your insights or the monthly report',
      summary: 'What changed, what stands out and what repeats in your spending, worded by the local AI but checked by code.',
      steps: [
        { actor: 'app', label: 'Find what changed', detail: 'Changes of 10% or more.' },
        { actor: 'app', label: 'Spot unusually large purchases', detail: '3× the category’s typical (median) amount.' },
        { actor: 'app', label: 'Find recurring payments, when you ask', detail: '3 or more times, weekly, monthly, quarterly or yearly, with the amount stable within 15%. You confirm or dismiss each one.' },
        { actor: 'app', label: 'Add the budget warnings' },
        { actor: 'ai', label: 'The local AI rewords each insight' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Do its numbers check out?',
          branches: [{ when: 'No', then: 'The rewording is dropped and the plain computed sentence is shown.', tone: 'warn' }],
          yes: 'Sentence kept',
        },
        { actor: 'app', label: 'The monthly report', detail: 'Summary, categories, 50/30/20, budgets and net worth, as printable tables.' },
        {
          actor: 'app',
          label: 'Everything stays local',
          detail: 'Everything runs on your computer; the AI and OCR have no internet access. The only download is a model update you choose to make.',
        },
      ],
      outputs: ['Checked insights', 'A printable monthly report'],
    },
  ],
};

const ro: WorkflowSet = {
  intro:
    'BANKY rulează șapte fluxuri, toate pe calculatorul tău. Primele patru le pornești tu: imporți un extras, îi confirmi rândurile, le sortezi, atașezi un bon. Bugetele, obiectivele și analizele citesc apoi registrul tău. Alege unul ca să-l urmărești pas cu pas.',
  workflows: [
    {
      id: 'import',
      title: 'Importul unui extras',
      trigger: 'Când încarci un extras bancar',
      summary: 'Extrasul e transformat în rânduri pe care le verifici tu: prin reguli fixe pentru PDF-urile cu text și foile de calcul, și prin OCR plus AI-ul local doar pentru scanări.',
      steps: [
        { actor: 'app', label: 'Recunoaște fișierul', detail: 'După conținutul lui.' },
        {
          kind: 'decision',
          actor: 'store',
          label: 'Fișierul a mai fost importat?',
          branches: [{ when: 'Da', then: 'Refuzat, cu data primului import.', tone: 'bad' }],
          yes: 'Fișier nou',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Ce fel de fișier?',
          branches: [
            {
              when: 'PDF cu text',
              then: 'Citit după regulile de așezare ale băncii (ING sau un cititor general), fără AI. Intrarea sau ieșirea banilor vine din coloanele de debit și credit; fără antet de coloană, suma e lăsată goală, cu un avertisment.',
            },
            {
              when: 'Foaie de calcul, CSV sau HTML',
              then: 'Un cititor de tabele, fără AI: credit minus debit sau sensul dedus din sold. Un sold care nu se potrivește dă un avertisment.',
            },
          ],
          yes: 'Scanare sau imagine',
        },
        { actor: 'app', label: 'Pagina e citită cu OCR', detail: 'La 300 dpi, curățată și îndreptată.' },
        { actor: 'ai', label: 'AI-ul local așază textul în rânduri', detail: 'Doar așază ce a citit OCR-ul din pagină.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Fiecare număr, verificat pe pagină',
          detail: 'Fiecare sumă trebuie să fie egală cu un număr tipărit pe pagină; și data e verificată.',
          branches: [
            { when: 'Numărul nu e pe pagină', then: 'Lăsat gol, cu un avertisment.', tone: 'warn' },
            { when: 'Semnul minus nu e tipărit', then: 'Avertisment.', tone: 'warn' },
            { when: 'Un caracter citit sub 80% încredere', then: '„Confirmă tu.”', tone: 'warn' },
          ],
          yes: 'Se potrivește cu pagina',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'S-a putut citi ceva?',
          branches: [{ when: 'Nu', then: 'Fișierul e șters, cu un mesaj clar.', tone: 'bad' }],
          yes: 'Rânduri citite',
        },
        {
          kind: 'decision',
          actor: 'store',
          label: 'Există deja în registru?',
          detail: 'Aceeași dată, sumă și descriere.',
          branches: [{ when: 'Da', then: 'Marcat ca posibil duplicat, niciodată eliminat.', tone: 'warn' }],
          yes: 'Rând nou',
        },
        { actor: 'store', label: 'Rândurile îți așteaptă verificarea', goto: 'review' },
      ],
      outputs: ['Rânduri care așteaptă verificarea ta', 'Un avertisment la tot ce e nesigur'],
      feeds: ['review'],
    },
    {
      id: 'review',
      title: 'Verificare și confirmare',
      trigger: 'După fiecare import',
      summary: 'Verifici fiecare rând cu originalul înainte ca ceva să ajungă în registrul tău.',
      steps: [
        { actor: 'app', label: 'Originalul, alături', detail: 'Rândul la care ești e evidențiat pe extras.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Rândul e curat?',
          branches: [{ when: 'Are avertismente sau vine dintr-o scanare', then: 'Îl verifici întâi, apoi îl confirmi împreună cu celelalte rânduri pe care le selectezi.', tone: 'warn' }],
          yes: 'Curat: confirmat dintr-un clic',
        },
        { actor: 'you', label: 'Lucrezi din tastatură', detail: 'j, k, Enter, e și r.' },
        { actor: 'you', label: 'Editezi un rând', detail: 'Verificarea de duplicat se reia pe noile valori.' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Confirmi sau respingi?',
          branches: [{ when: 'Respingi', then: 'Nu se scrie nimic.', tone: 'bad' }],
          yes: 'Confirmi',
        },
        { actor: 'store', label: 'Scris în registru', detail: 'Banii ieșiți sunt înregistrați ca cheltuială.', goto: 'categorise' },
        { actor: 'you', label: 'Sau o iei de la capăt', detail: 'Renunți la tot importul sau convertești extrasul în Excel, îl corectezi și îl imporți din nou.' },
      ],
      outputs: ['Tranzacții confirmate în registrul tău'],
      feeds: ['categorise'],
    },
    {
      id: 'categorise',
      title: 'Categorizare',
      trigger: 'Când ceri',
      summary: 'Regulile tale sortează ce pot; pentru rest, AI-ul local propune o categorie, doar din lista ta.',
      steps: [
        { actor: 'app', label: 'Întâi regulile tale', detail: 'Potrivire exactă, „conține” sau tipar. O potrivire cu o regulă e sigură.' },
        { actor: 'ai', label: 'Restul merge la AI-ul local', detail: 'Câte 15 odată, cu lista ta de categorii ca singurele răspunsuri permise.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Categoria e pe lista ta?',
          branches: [{ when: 'Inventată', then: 'Eliminată.', tone: 'bad' }],
          yes: 'Pe lista ta',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Cât de sigur e?',
          branches: [
            { when: 'Sub 0,50', then: 'Fără categorie.', tone: 'bad' },
            { when: '0,50 sau mai mult', then: 'Afișată ca sugestie.', tone: 'warn' },
            { when: '0,80 sau mai mult, în registru', then: 'Aplicată.', tone: 'ok' },
          ],
        },
        { actor: 'you', label: 'Accepți restul dintr-odată', detail: 'Sugestiile rămase pot fi acceptate împreună.' },
        {
          kind: 'loop',
          actor: 'you',
          label: 'Schimbi o categorie în registru: se scrie o regulă',
          detail: 'Noua regulă folosește chiar textul băncii pentru acea tranzacție, așa că de acum o sortează regulile tale.',
        },
      ],
      outputs: ['Tranzacții pe categorii', 'Reguli învățate din corecturile tale'],
      feeds: ['budgets', 'insights'],
    },
    {
      id: 'receipts',
      title: 'Bonuri',
      trigger: 'Când atașezi un bon la o tranzacție',
      summary: 'Produsele de pe bon sunt citite, apoi verificate pe pagină și cu tranzacția.',
      steps: [
        { actor: 'you', label: 'Atașezi o fotografie sau un PDF', detail: 'La o tranzacție din registrul tău.' },
        { actor: 'app', label: 'Bonul e citit cu OCR' },
        { actor: 'ai', label: 'AI-ul local listează produsele', detail: 'Așază în rânduri de produse ce a citit OCR-ul.' },
        { actor: 'app', label: 'Verifică fiecare cantitate și preț', detail: 'Fiecare, pe pagină.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Produsele dau totalul?',
          branches: [{ when: 'Nu', then: 'O frază îți spune asta.', tone: 'warn' }],
          yes: 'Da',
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Totalul e egal cu tranzacția?',
          detail: 'Exact.',
          branches: [{ when: 'Nu', then: 'O frază îți spune asta.', tone: 'warn' }],
          yes: 'Da',
        },
        { actor: 'you', label: 'Verifici rândurile', detail: 'Verificarea unui bon nu mută niciodată bani.' },
      ],
      outputs: ['Un bon pe produse, verificat cu tranzacția lui'],
    },
    {
      id: 'budgets',
      title: 'Bugete și 50/30/20',
      trigger: 'Pentru fiecare buget lunar pe care îl setezi',
      summary: 'Un buget lunar pe categorie, cu avertisment înainte să depășești, și împărțirea 50/30/20 a ultimei luni întregi.',
      steps: [
        { actor: 'you', label: 'Setezi un buget lunar pe categorie principală' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Cât s-a cheltuit?',
          branches: [
            { when: 'Sub 75%', then: 'În regulă.', tone: 'ok' },
            { when: '75% sau mai mult', then: 'Aproape de limită.', tone: 'warn' },
            { when: '100% sau mai mult', then: 'Depășit, cu avertisment.', tone: 'bad' },
          ],
        },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Mai repede decât ritmul lunii?',
          branches: [{ when: 'Cu peste 25 de puncte înainte', then: 'Avertisment.', tone: 'warn' }],
          yes: 'În ritm',
        },
        {
          actor: 'app',
          label: '50/30/20 pentru ultima lună întreagă',
          detail: 'Nevoi, dorințe și economii. Economiile sunt exacte; nevoile și dorințele apar ca intervale cât timp o parte din cheltuieli nu are categorie.',
        },
        { actor: 'app', label: 'Avertismentele ajung în analize', goto: 'insights' },
      ],
      outputs: ['Starea fiecărui buget', 'Împărțirea ta 50/30/20'],
      feeds: ['insights'],
    },
    {
      id: 'goals',
      title: 'Obiective și investiții',
      trigger: 'Când setezi un obiectiv sau înregistrezi o evaluare',
      summary: 'Banii din conturile de obiective îți umplu obiectivele în ordinea priorității, cu suma lunară și data estimată pentru fiecare.',
      steps: [
        { actor: 'you', label: 'Înregistrezi evaluarea unei investiții', detail: 'Unități × preț, plus numerar. Instantaneul înlocuiește soldul contului.' },
        { actor: 'store', label: 'Se adună conturile de obiective', detail: 'Investițiile contează la ultima lor evaluare.' },
        { actor: 'app', label: 'Obiectivele se umplu în ordinea priorității tale' },
        { actor: 'app', label: 'Se calculează suma pe lună', detail: 'Cât trebuie să pui deoparte lunar ca să atingi fiecare obiectiv la data lui.' },
        { actor: 'app', label: 'Se estimează datele', detail: 'Din economia ta lunară obișnuită: mediana ultimelor 12 luni.' },
        { actor: 'ai', label: 'Comentariu AI, opțional', detail: 'Schițat, verificat, criticat, revizuit și verificat din nou.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Fiecare număr se regăsește în date?',
          branches: [{ when: 'Nu', then: 'Comentariul e respins. Dacă niciunul nu trece, primești doar cifrele.', tone: 'bad' }],
          yes: 'Comentariu afișat',
        },
      ],
      outputs: ['Progresul fiecărui obiectiv', 'Suma necesară pe lună', 'Datele estimate'],
    },
    {
      id: 'insights',
      title: 'Analize și raportul lunar',
      trigger: 'Când deschizi analizele sau raportul lunar',
      summary: 'Ce s-a schimbat, ce iese în evidență și ce se repetă în cheltuielile tale, formulat de AI-ul local, dar verificat de cod.',
      steps: [
        { actor: 'app', label: 'Găsește ce s-a schimbat', detail: 'Schimbări de 10% sau mai mult.' },
        { actor: 'app', label: 'Observă cumpărăturile neobișnuit de mari', detail: 'De 3 ori suma obișnuită (mediana) a categoriei.' },
        { actor: 'app', label: 'Găsește plățile recurente, când ceri', detail: 'De 3 sau mai multe ori, săptămânal, lunar, trimestrial sau anual, cu suma stabilă în limita a 15%. Confirmi sau respingi fiecare.' },
        { actor: 'app', label: 'Adaugă avertismentele de buget' },
        { actor: 'ai', label: 'AI-ul local reformulează fiecare analiză' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Cifrele ei se verifică?',
          branches: [{ when: 'Nu', then: 'Reformularea e ignorată și se afișează fraza calculată, simplă.', tone: 'warn' }],
          yes: 'Frază păstrată',
        },
        { actor: 'app', label: 'Raportul lunar', detail: 'Rezumat, categorii, 50/30/20, bugete și avere netă, în tabele de tipărit.' },
        {
          actor: 'app',
          label: 'Totul rămâne local',
          detail: 'Totul rulează pe calculatorul tău; AI-ul și OCR-ul nu au acces la internet. Singura descărcare e o actualizare de model pe care alegi tu s-o faci.',
        },
      ],
      outputs: ['Analize verificate', 'Un raport lunar de tipărit'],
    },
  ],
};

export default { en, ro };
