// CASES' workflows, traced from its source code (numbers are the code's defaults).
import type { WorkflowSet } from './types';

const en: WorkflowSet = {
  intro:
    'CASES runs seven workflows. Three build each case and prove it fair before anyone plays it; four are the game your team plays against the clock. Pick one to follow it step by step.',
  workflows: [
    {
      id: 'generate',
      title: 'Generate a case',
      trigger: 'When the admin asks for a new case',
      summary: 'The local AI writes a whole mystery, but the culprit is drawn by code, not by the model.',
      steps: [
        { actor: 'you', label: 'Choose the difficulty and a theme', detail: 'The admin picks the difficulty; the theme is optional.' },
        { actor: 'app', label: 'Draw the year', detail: 'From the eras the difficulty allows.' },
        { actor: 'ai', label: 'Write the premise' },
        { actor: 'app', label: 'Draw the culprit, by code', detail: 'Picked at random by code, never by the model.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Does the hidden truth name exactly the culprit?',
          detail: 'The local AI writes what really happened.',
          branches: [{ when: 'No', then: 'Written again, once.', tone: 'warn' }],
          yes: 'Yes',
        },
        {
          actor: 'ai',
          label: 'Build the world of the case',
          detail: 'Cast, places, evidence, lab results, interview topics, documents, records and the opening state. A liar’s confession is locked behind the clue that breaks the lie.',
        },
        { kind: 'loop', actor: 'app', label: 'Every reply checked against a strict format', detail: 'A model reply that does not fit is asked for again, up to 3 tries.' },
        { actor: 'app', label: 'Sent for the fairness checks', goto: 'prove' },
      ],
      outputs: ['A complete draft case', 'Its hidden truth'],
      feeds: ['prove'],
    },
    {
      id: 'prove',
      title: 'Prove it’s fair',
      trigger: 'Right after a case is generated',
      summary: 'Code checks that the case is consistent, true to its era and solvable; a case that fails is rejected and not saved.',
      steps: [
        { actor: 'app', label: 'Check the structure', detail: 'Every item has its own identity and the pieces fit together.' },
        { actor: 'app', label: 'Check the time', detail: 'Nobody is in two places at once, and the chain of custody (who held each piece of evidence) runs forward in time.' },
        { actor: 'app', label: 'Check the era', detail: 'Only tests that existed that year: no DNA before 1986.' },
        { actor: 'app', label: 'Check it can be solved', detail: 'Every proving clue can be reached from day one, and the quickest path takes no more than 50–60% of the time budget.' },
        { actor: 'app', label: 'Check it is fair', detail: 'Every lie can be broken, red herrings don’t carry the case, and no single record solves it.' },
        { kind: 'loop', actor: 'ai', label: 'Repair the earliest failing stage', detail: 'Written again with the problems as corrections, up to 4 times.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Still failing?',
          branches: [{ when: 'Yes', then: 'Rejected; nothing is saved.', tone: 'bad' }],
          yes: 'Passed',
        },
        { actor: 'store', label: 'Saved as ready', goto: 'illustrate' },
      ],
      outputs: ['A case proven fair and solvable'],
      feeds: ['illustrate'],
    },
    {
      id: 'illustrate',
      title: 'Illustrate and publish',
      trigger: 'After a case is saved',
      summary: 'A local image model paints the case in the look of its era, then the admin publishes it.',
      steps: [
        { actor: 'app', label: 'Put the pictures in order', detail: 'Portraits of the victim and suspects and the cover first, then the crime scene, the evidence, the witnesses and the rest.' },
        { actor: 'app', label: 'Swap the models', detail: 'One graphics card: the language model steps out and the image model steps in.' },
        { actor: 'ai', label: 'Paint each image', detail: 'With the local image model.' },
        { actor: 'app', label: 'Give it the look of the era', detail: 'A colour grade with grain, tint and vignette.' },
        { kind: 'loop', actor: 'app', label: 'If an image fails', detail: 'Retried 3 times, then marked as failed.' },
        { actor: 'you', label: 'The admin reviews and publishes', goto: 'start' },
      ],
      outputs: ['Portraits, scenes and evidence images', 'A published case'],
      feeds: ['start'],
    },
    {
      id: 'start',
      title: 'Start the clock',
      trigger: 'When your team opens a published case',
      summary: 'Your team picks a case and the clock starts; every action spends in-game time.',
      steps: [
        { actor: 'you', label: 'Choose a published case' },
        { actor: 'you', label: 'Name your team' },
        { kind: 'schedule', actor: 'app', label: 'The clock runs', detail: 'For example, 90 minutes of play are 10 days in the game.' },
        { actor: 'app', label: 'Every action costs time' },
        { actor: 'you', label: 'Pause and resume' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Any time left?',
          branches: [{ when: 'Time runs out', then: 'The case is closed.', tone: 'bad' }],
          yes: 'Yes',
        },
        { actor: 'you', label: 'On to the investigation', goto: 'investigate' },
      ],
      outputs: ['A running case clock'],
      feeds: ['investigate'],
    },
    {
      id: 'investigate',
      title: 'Investigate',
      trigger: 'While the clock runs',
      summary: 'Interview, search, send evidence to the lab and request records; everything costs time.',
      steps: [
        { actor: 'you', label: 'Interview people', detail: 'Each question costs minutes. New questions unlock as you find things, each with a note on why you can ask it.' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Challenge a lie with a finding',
          branches: [
            { when: 'The right finding', then: 'A confession.', tone: 'ok' },
            { when: 'The wrong finding', then: 'It counts against you at trial.', tone: 'bad' },
          ],
        },
        { actor: 'ai', label: 'Talk freely', detail: 'You can have an open conversation; the person never names the culprit.' },
        { actor: 'you', label: 'Search places', detail: 'Each search costs time.' },
        { kind: 'schedule', actor: 'app', label: 'Send evidence to the lab', detail: '3 benches. How long it takes depends on the test: fingerprints are fast, DNA the slowest. Then you collect the report.' },
        { kind: 'schedule', actor: 'app', label: 'Request records', detail: 'You wait, then collect them.' },
        { actor: 'you', label: 'Keep notes' },
        { actor: 'ai', label: 'Ask the file', detail: 'Answers come only from what you have found.' },
        { actor: 'you', label: 'Print the kit', detail: 'The case as A4 pages for the table: cover, briefing, map, places, exhibits and lab reports. Only what your team has found.' },
        { actor: 'you', label: 'File your report', goto: 'report' },
      ],
      outputs: ['Findings, lab reports and records', 'Confessions'],
      feeds: ['report'],
    },
    {
      id: 'report',
      title: 'File the report',
      trigger: 'When your team files its report',
      summary: 'Code weighs your accusation and your evidence, then gives a verdict and a score out of 100.',
      steps: [
        { actor: 'you', label: 'Write the report', detail: 'The accused, the motive, the method, your exhibits and the order of events.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Can each exhibit be used?',
          branches: [
            { when: 'Never found, or a red herring', then: 'Excluded.', tone: 'bad' },
            { when: 'Broken chain of custody, or not lab-tested', then: 'Challenged.', tone: 'warn' },
          ],
          yes: 'Otherwise admitted',
        },
        { actor: 'app', label: 'Score the evidence and the timeline', detail: 'How strong your evidence is, and your order of events.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'The verdict, decided by code',
          branches: [
            { when: 'Nobody named', then: 'The case goes cold.', tone: 'warn' },
            { when: 'An innocent named', then: 'Wrongful accusation.', tone: 'bad' },
            { when: 'Evidence strength under 0.35', then: 'Insufficient evidence.', tone: 'bad' },
            { when: 'All culprits named, strength 0.75+, timeline 0.6+', then: 'Conviction.', tone: 'ok' },
            { when: 'Otherwise', then: 'Charges filed.' },
          ],
        },
        { actor: 'app', label: 'Score out of 100', detail: '40 points for naming the culprit, 45 for the evidence and 15 for the timeline.' },
        { actor: 'app', label: 'To court', goto: 'trial' },
      ],
      outputs: ['A verdict', 'A score out of 100'],
      feeds: ['trial'],
    },
    {
      id: 'trial',
      title: 'The trial',
      trigger: 'After your report is judged',
      summary: 'Your case is played out in court in 8 beats, ending with the whole truth.',
      steps: [
        { actor: 'app', label: 'The court sits' },
        { actor: 'app', label: 'The prosecution', detail: 'Your motive, method and account of events, read out.' },
        { actor: 'app', label: 'The exhibits', detail: 'Admitted, challenged or excluded, each with its reason.' },
        { actor: 'app', label: 'Cross-examination', detail: 'Missing clues, broken custody and lies you never challenged come out.' },
        { actor: 'app', label: 'The witnesses', detail: 'Liars you caught take back their story.' },
        { actor: 'app', label: 'Deliberation' },
        { actor: 'app', label: 'The verdict' },
        { actor: 'app', label: 'Epilogue', detail: 'The whole truth of what happened.' },
      ],
      outputs: ['The trial, beat by beat', 'The whole truth'],
    },
  ],
};

const ro: WorkflowSet = {
  intro:
    'CASES rulează șapte fluxuri. Trei construiesc fiecare caz și dovedesc că e corect înainte să-l joace cineva; patru sunt jocul pe care echipa ta îl joacă împotriva ceasului. Alege unul ca să-l urmărești pas cu pas.',
  workflows: [
    {
      id: 'generate',
      title: 'Generarea unui caz',
      trigger: 'Când administratorul cere un caz nou',
      summary: 'AI-ul local scrie un mister întreg, dar vinovatul e tras la sorți de cod, nu de model.',
      steps: [
        { actor: 'you', label: 'Alegi dificultatea și o temă', detail: 'Administratorul alege dificultatea; tema e opțională.' },
        { actor: 'app', label: 'Trage la sorți anul', detail: 'Dintre epocile permise de dificultate.' },
        { actor: 'ai', label: 'Scrie premisa' },
        { actor: 'app', label: 'Trage la sorți vinovatul, prin cod', detail: 'Ales la întâmplare de cod, niciodată de model.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Adevărul ascuns numește exact vinovatul?',
          detail: 'AI-ul local scrie ce s-a întâmplat de fapt.',
          branches: [{ when: 'Nu', then: 'Rescris, o dată.', tone: 'warn' }],
          yes: 'Da',
        },
        {
          actor: 'ai',
          label: 'Construiește lumea cazului',
          detail: 'Personaje, locuri, probe, rezultate de laborator, subiecte de interogatoriu, documente, registre și situația de pornire. Mărturisirea unui mincinos e blocată în spatele indiciului care îi demontează minciuna.',
        },
        { kind: 'loop', actor: 'app', label: 'Fiecare răspuns, verificat după un format strict', detail: 'Un răspuns al modelului care nu se potrivește e cerut din nou, de până la 3 ori.' },
        { actor: 'app', label: 'Trimis la verificările de corectitudine', goto: 'prove' },
      ],
      outputs: ['Un caz complet, în ciornă', 'Adevărul lui ascuns'],
      feeds: ['prove'],
    },
    {
      id: 'prove',
      title: 'Dovada că e corect',
      trigger: 'Imediat după generarea cazului',
      summary: 'Codul verifică dacă un caz e coerent, fidel epocii și rezolvabil; un caz care nu trece e respins și nu se salvează.',
      steps: [
        { actor: 'app', label: 'Verifică structura', detail: 'Fiecare element are identitatea lui, iar piesele se potrivesc între ele.' },
        { actor: 'app', label: 'Verifică timpul', detail: 'Nimeni nu e în două locuri deodată, iar lanțul de custodie (cine a avut fiecare probă) merge înainte în timp.' },
        { actor: 'app', label: 'Verifică epoca', detail: 'Doar teste care existau în acel an: fără ADN înainte de 1986.' },
        { actor: 'app', label: 'Verifică dacă se poate rezolva', detail: 'Fiecare indiciu decisiv e accesibil din prima zi, iar drumul cel mai scurt ia cel mult 50–60% din timpul disponibil.' },
        { actor: 'app', label: 'Verifică dacă e corect', detail: 'Orice minciună poate fi demontată, pistele false nu susțin cazul și niciun registru singur nu îl rezolvă.' },
        { kind: 'loop', actor: 'ai', label: 'Repară prima etapă care eșuează', detail: 'Rescrisă cu problemele drept corecturi, de până la 4 ori.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Tot nu trece?',
          branches: [{ when: 'Da', then: 'Respins; nu se salvează nimic.', tone: 'bad' }],
          yes: 'Trecut',
        },
        { actor: 'store', label: 'Salvat ca pregătit', goto: 'illustrate' },
      ],
      outputs: ['Un caz dovedit corect și rezolvabil'],
      feeds: ['illustrate'],
    },
    {
      id: 'illustrate',
      title: 'Ilustrare și publicare',
      trigger: 'După salvarea cazului',
      summary: 'Un model local de imagini pictează cazul în stilul epocii lui, apoi administratorul îl publică.',
      steps: [
        { actor: 'app', label: 'Ordonează imaginile', detail: 'Întâi portretele victimei și ale suspecților și coperta, apoi locul crimei, probele, martorii și restul.' },
        { actor: 'app', label: 'Schimbă modelele', detail: 'O singură placă grafică: modelul de limbaj iese, modelul de imagini intră.' },
        { actor: 'ai', label: 'Pictează fiecare imagine', detail: 'Cu modelul local de imagini.' },
        { actor: 'app', label: 'Îi dă aspectul epocii', detail: 'O corecție de culoare cu granulație, nuanță și vignetă.' },
        { kind: 'loop', actor: 'app', label: 'Dacă o imagine eșuează', detail: 'Reîncercată de 3 ori, apoi marcată ca eșuată.' },
        { actor: 'you', label: 'Administratorul verifică și publică', goto: 'start' },
      ],
      outputs: ['Portrete, scene și imagini ale probelor', 'Un caz publicat'],
      feeds: ['start'],
    },
    {
      id: 'start',
      title: 'Pornirea ceasului',
      trigger: 'Când echipa ta deschide un caz publicat',
      summary: 'Echipa ta alege un caz și ceasul pornește; fiecare acțiune consumă timp din joc.',
      steps: [
        { actor: 'you', label: 'Alegi un caz publicat' },
        { actor: 'you', label: 'Dai un nume echipei' },
        { kind: 'schedule', actor: 'app', label: 'Ceasul merge', detail: 'De exemplu, 90 de minute de joc înseamnă 10 zile în poveste.' },
        { actor: 'app', label: 'Fiecare acțiune costă timp' },
        { actor: 'you', label: 'Pauză și reluare' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Mai e timp?',
          branches: [{ when: 'Timpul s-a terminat', then: 'Cazul se închide.', tone: 'bad' }],
          yes: 'Da',
        },
        { actor: 'you', label: 'Treci la anchetă', goto: 'investigate' },
      ],
      outputs: ['Ceasul cazului, în mers'],
      feeds: ['investigate'],
    },
    {
      id: 'investigate',
      title: 'Ancheta',
      trigger: 'Cât timp merge ceasul',
      summary: 'Interoghezi, cauți, trimiți probe la laborator și ceri registre; totul costă timp.',
      steps: [
        { actor: 'you', label: 'Interoghezi oamenii', detail: 'Fiecare întrebare costă minute. Întrebările noi se deblochează pe măsură ce descoperi lucruri, fiecare cu o notă despre de ce o poți pune.' },
        {
          kind: 'decision',
          actor: 'you',
          label: 'Contești o minciună cu o descoperire',
          branches: [
            { when: 'Descoperirea potrivită', then: 'O mărturisire.', tone: 'ok' },
            { when: 'Descoperirea greșită', then: 'Contează împotriva ta la proces.', tone: 'bad' },
          ],
        },
        { actor: 'ai', label: 'Vorbești liber', detail: 'Poți purta o conversație deschisă; persoana nu îl numește niciodată pe vinovat.' },
        { actor: 'you', label: 'Cauți în locuri', detail: 'Fiecare căutare costă timp.' },
        { kind: 'schedule', actor: 'app', label: 'Trimiți probe la laborator', detail: '3 mese de lucru. Durata depinde de test: amprentele sunt rapide, ADN-ul cel mai lent. Apoi ridici raportul.' },
        { kind: 'schedule', actor: 'app', label: 'Ceri registre', detail: 'Aștepți, apoi le ridici.' },
        { actor: 'you', label: 'Îți iei notițe' },
        { actor: 'ai', label: 'Întrebi dosarul', detail: 'Răspunsurile vin doar din ce ai descoperit.' },
        { actor: 'you', label: 'Tipărești kitul', detail: 'Cazul pe pagini A4, pentru masă: copertă, briefing, hartă, locuri, probe și rapoarte de laborator. Doar ce a găsit echipa ta.' },
        { actor: 'you', label: 'Depui raportul', goto: 'report' },
      ],
      outputs: ['Descoperiri, rapoarte de laborator și registre', 'Mărturisiri'],
      feeds: ['report'],
    },
    {
      id: 'report',
      title: 'Depunerea raportului',
      trigger: 'Când echipa ta depune raportul',
      summary: 'Codul cântărește acuzația și probele tale, apoi dă un verdict și un scor din 100.',
      steps: [
        { actor: 'you', label: 'Scrii raportul', detail: 'Acuzatul, mobilul, metoda, probele tale și ordinea evenimentelor.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Poate fi folosită fiecare probă?',
          branches: [
            { when: 'Negăsită niciodată sau pistă falsă', then: 'Exclusă.', tone: 'bad' },
            { when: 'Lanț de custodie rupt sau netestată în laborator', then: 'Contestată.', tone: 'warn' },
          ],
          yes: 'Altfel admisă',
        },
        { actor: 'app', label: 'Punctează probele și cronologia', detail: 'Cât de puternice sunt probele tale și ordinea evenimentelor.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Verdictul, decis de cod',
          branches: [
            { when: 'Nu e numit nimeni', then: 'Cazul rămâne nerezolvat.', tone: 'warn' },
            { when: 'E numit un nevinovat', then: 'Acuzare pe nedrept.', tone: 'bad' },
            { when: 'Forța probelor sub 0,35', then: 'Probe insuficiente.', tone: 'bad' },
            { when: 'Toți vinovații numiți, forță de minimum 0,75, cronologie de minimum 0,6', then: 'Condamnare.', tone: 'ok' },
            { when: 'Altfel', then: 'Punere sub acuzare.' },
          ],
        },
        { actor: 'app', label: 'Scor din 100', detail: '40 de puncte pentru identificarea vinovatului, 45 pentru probe și 15 pentru cronologie.' },
        { actor: 'app', label: 'La tribunal', goto: 'trial' },
      ],
      outputs: ['Un verdict', 'Un scor din 100'],
      feeds: ['trial'],
    },
    {
      id: 'trial',
      title: 'Procesul',
      trigger: 'După ce raportul tău e judecat',
      summary: 'Cazul tău se joacă în instanță în 8 momente și se încheie cu tot adevărul.',
      steps: [
        { actor: 'app', label: 'Instanța intră în ședință' },
        { actor: 'app', label: 'Acuzarea', detail: 'Mobilul, metoda și relatarea voastră, citite în instanță.' },
        { actor: 'app', label: 'Probele', detail: 'Acceptate, contestate sau excluse, fiecare cu motivul ei.' },
        { actor: 'app', label: 'Contrainterogatoriul', detail: 'Ies la iveală indiciile lipsă, custodia ruptă și minciunile pe care nu le-ai contestat.' },
        { actor: 'app', label: 'Martorii', detail: 'Mincinoșii prinși își retrag declarațiile.' },
        { actor: 'app', label: 'Deliberarea' },
        { actor: 'app', label: 'Verdictul' },
        { actor: 'app', label: 'Epilogul', detail: 'Tot adevărul despre ce s-a întâmplat.' },
      ],
      outputs: ['Procesul, moment cu moment', 'Tot adevărul'],
    },
  ],
};

export default { en, ro };
