// COUNSELOR's workflows, traced from its source code (numbers are the code's defaults).
import type { WorkflowSet } from './types';

const en: WorkflowSet = {
  intro:
    'COUNSELOR runs eight workflows on your own server. Most start on their own, on a schedule; the rest start when you open a screen or ask for something. Pick one to follow it step by step.',
  workflows: [
    {
      id: 'collect',
      title: 'Collect the news',
      trigger: 'Every 5 minutes; each source is checked every 15',
      summary: 'New articles are found in your sources: from their RSS feed, or by reading the front page when there is no feed.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Which sources are due?', detail: 'A source is due 15 minutes after its last check. A source that keeps failing waits twice as long each time, up to 16×.' },
        { actor: 'ext', label: 'Ask the source for anything new', detail: 'Only changes are requested: an unchanged source answers "not modified" and nothing more is downloaded. 30-second limit.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Does the source have a feed?',
          branches: [{ when: 'No feed', then: 'The front page is read for article links: same site, a headline of 15+ characters, up to 120 links.' }],
          yes: 'Feed: title, link, author, date and picture are read',
        },
        { kind: 'decision', actor: 'store', label: 'Seen this link before?', branches: [{ when: 'Yes', then: 'Skipped.' }], yes: 'New link' },
        { actor: 'store', label: 'Saved as a new article', goto: 'read' },
        { actor: 'you', label: 'Adding a source', detail: 'Paste any address. If it is a feed, or the page points to one, it is added as RSS; otherwise the page itself is read. If no articles are found, you are told.' },
      ],
      outputs: ['New articles, waiting to be read'],
      feeds: ['read'],
    },
    {
      id: 'read',
      title: 'Read each article',
      trigger: 'Right after it is collected',
      summary: 'The full page is downloaded and turned into clean text, with its picture and language.',
      steps: [
        { actor: 'ext', label: 'Download the article page', detail: '30-second limit.' },
        { actor: 'app', label: 'Find the lead picture', detail: 'From the page’s own sharing tags, before the text, so paywalled pages still give a picture.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Is there readable text?',
          branches: [{ when: 'No (paywall or script-only page)', then: 'It carries on with the headline only; the per-article analysis skips it.', tone: 'warn' }],
          yes: 'Clean text extracted',
        },
        { kind: 'decision', actor: 'store', label: 'Same text already stored?', branches: [{ when: 'Yes', then: 'Marked as a duplicate; it stops here.' }], yes: 'New text' },
        { actor: 'app', label: 'Detect the language', detail: 'Romanian, English, German, French, Spanish, Italian, Russian or Ukrainian; otherwise the source’s declared language.' },
        { actor: 'store', label: 'Keep the text, drop the raw page', goto: 'group' },
        { kind: 'loop', actor: 'app', label: 'If the download fails', detail: 'Retried 3 times, 2 minutes apart, then again every 30 minutes.' },
      ],
      outputs: ['Clean text, picture and language for every article'],
      feeds: ['group'],
    },
    {
      id: 'group',
      title: 'Group into stories',
      trigger: 'Right after an article is read',
      summary: 'Articles about the same event, from any outlet and in any language, are gathered into one story.',
      steps: [
        { actor: 'ai', label: 'Turn the article into a meaning vector', detail: 'Headline plus text. The model is multilingual, so a Romanian and an English report of the same event land close together.' },
        { actor: 'store', label: 'Find the closest articles', detail: 'Among articles published within 72 hours of this one.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Similar enough (0.78 or more)?',
          branches: [{ when: 'No', then: 'A new story starts with this article.' }],
          yes: 'It joins that story (unless the story is retired)',
        },
        { actor: 'app', label: 'The story is marked for analysis', detail: 'Stories only ever gain articles; they are never split or regrouped.', goto: 'understand' },
        { kind: 'loop', actor: 'app', label: 'Safety net before each briefing', detail: 'Articles left on their own for 45 minutes are matched by headline words: at least a third in common, and 2 or more shared words.' },
      ],
      outputs: ['Stories that follow one event across outlets'],
      feeds: ['understand'],
    },
    {
      id: 'understand',
      title: 'Understand each story',
      trigger: 'Checked every 3 minutes',
      summary: 'Once a story has settled, the local AI reads its articles and writes what happened, what is known and what is not.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Which stories are ready?', detail: 'Ready when 2 or more outlets report it, or 20 minutes have passed. Up to 100 at a time, mostly the newest.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'How many outlets?',
          branches: [
            { when: 'One', then: 'The smaller model, without viewpoints or consensus, so no contrast is invented.' },
            { when: 'Several', then: 'The larger model.', tone: 'ok' },
          ],
          yes: 'Then',
        },
        { actor: 'ai', label: 'Read up to 15 articles', detail: '2,000 characters each, with each outlet’s known political leaning.' },
        {
          actor: 'ai',
          label: 'Write the analysis',
          detail: 'Short, medium and detailed summaries; key facts; what we know and what we don’t; viewpoints; quotes; people, organisations and places; 1–3 categories. The country of the event sets the region.',
        },
        { actor: 'app', label: 'Measure, without AI', detail: 'How the outlets spread across the spectrum, and a confidence score from the number of sources and leanings.' },
        { actor: 'store', label: 'Save the new version', detail: 'The previous one stays in the story’s history.', goto: 'score' },
        { kind: 'loop', actor: 'app', label: 'Analysed again as it grows', detail: 'After 45 quiet minutes and at least 50% more articles. Idle for 48 hours: retired.' },
        {
          actor: 'ai',
          label: 'Every article, in parallel',
          detail: 'Every 5 minutes the smaller model writes each article’s neutral summary, its own framing (left, centre or right, and why), 2–4 checkable claims and a Romanian headline. Failures are retried up to 3 times.',
          goto: 'factcheck',
        },
      ],
      outputs: ['Summaries in three lengths', 'What we know / what we don’t', 'Viewpoints and quotes', 'Source spectrum and confidence'],
      feeds: ['score', 'factcheck'],
    },
    {
      id: 'score',
      title: 'Score and alert',
      trigger: 'After each story analysis',
      summary: 'Every story gets an importance score from 0 to 100; the important ones reach you as an alert.',
      steps: [
        {
          actor: 'app',
          label: 'Score importance, by arithmetic',
          detail: 'Sources up to 30 points, source credibility 15, countries involved 15, government or military 15, money 10, your chosen categories 10, speed of spread 5.',
        },
        { kind: 'decision', actor: 'app', label: 'Above your threshold?', branches: [{ when: 'Below (default 60)', then: 'It stays on the dashboard, without an alert.' }], yes: 'Above' },
        { kind: 'decision', actor: 'store', label: 'Already alerted for this story?', branches: [{ when: 'Yes', then: 'No second alert.' }], yes: 'First time' },
        { actor: 'ai', label: 'Write why it matters', detail: 'One or two sentences from the larger model; a standard sentence if it fails.' },
        { actor: 'app', label: 'Deliver the alert', detail: 'A push notification to your devices, and an email if configured. The open app shows it too.' },
        { actor: 'app', label: 'Importance bands', detail: 'Critical, high, elevated and normal are relative: the top 3%, 10% and 25% of current stories.' },
      ],
      outputs: ['Alerts on your phone and computer', 'An importance score on every story'],
    },
    {
      id: 'briefing',
      title: 'Write the briefing',
      trigger: 'Every day at 07:00, every 4 hours, or when you ask',
      summary: 'A report on the period: the main stories, Romania and the world, deep dives and fact-checks.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Pick the period', detail: 'The morning briefing covers 24 hours; the rolling ones the last 6 hours; or any day you choose.' },
        { actor: 'app', label: 'Group any articles still on their own' },
        { actor: 'app', label: 'Rank the stories', detail: 'The top 5 in each category, and the 13 most important overall.' },
        {
          actor: 'ai',
          label: 'Write the report',
          detail: 'The larger model writes the summary and the deep dives: what happened, why it matters, where outlets differ, what is still unclear. If it fails, an overview is still produced from the data.',
        },
        { actor: 'ai', label: 'Romania and International', detail: 'Two separate sections, so Romanian news is not crowded out on busy days.' },
        { actor: 'app', label: 'Check the claims', goto: 'factcheck' },
        { actor: 'app', label: 'Counted, not written', detail: 'The evidence behind each deep dive, what changed since the last briefing, and the emerging topics come straight from the data.' },
        { actor: 'store', label: 'Save with a reference number', detail: 'For example RAP-2026-09-26-M01. The PDF is produced when you download it.' },
      ],
      outputs: ['The briefing on screen', 'PDF', 'Emerging topics', 'Fact-checks'],
      feeds: ['factcheck'],
    },
    {
      id: 'factcheck',
      title: 'Check the claims',
      trigger: 'Inside every briefing',
      summary: 'The AI proposes claims worth checking, but code decides every verdict from what other outlets reported.',
      steps: [
        { actor: 'ai', label: 'Claims are proposed', detail: 'The larger model suggests claims to check. Any verdict it offers is thrown away.' },
        { actor: 'store', label: 'Find matching reporting', detail: 'Each claim is compared with the claims taken from every analysed article, within 72 hours, keeping matches of 0.72 or more.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Can each quote count?',
          branches: [{ when: 'Unknown outlet', then: 'Dropped rather than cited under a guessed name.', tone: 'bad' }],
          yes: 'The strongest quote per outlet is kept',
        },
        { actor: 'ai', label: 'Label each quote', detail: 'Supports the claim, contradicts it, or is unrelated. The model is told not to decide the verdict.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'The verdict, decided by code',
          branches: [
            { when: 'Any contradiction', then: 'Disputed, naming who contradicts it.', tone: 'warn' },
            { when: 'Two or more support it', then: 'Confirmed.', tone: 'ok' },
            { when: 'One supports it', then: 'Single source.' },
            { when: 'None', then: 'Unverifiable, also when there is no evidence yet.' },
          ],
        },
      ],
      outputs: ['A verdict for every claim, with the outlets behind it'],
    },
    {
      id: 'screens',
      title: 'Your screens',
      trigger: 'Whenever you open the app',
      summary: 'What you see, and how it keeps itself up to date.',
      steps: [
        { actor: 'you', label: 'The dashboard', detail: 'Each panel refreshes on its own (alerts every minute, the AI panel every 10 seconds) and pauses when the tab is hidden.' },
        {
          actor: 'app',
          label: 'The world map',
          detail: 'Each story is placed in its country: from the headline first, then the rarest places it mentions. Stories with no country stay off the map. New unread stories (under 6 hours) blink, up to 12.',
        },
        { actor: 'you', label: 'A story', detail: 'Marked as read after 1.5 seconds. Any analysis step can be run again.' },
        { actor: 'you', label: 'Search, saved and read later', detail: 'Search by words in titles, people and summaries.' },
        { actor: 'app', label: 'What the AI is doing', detail: 'Live jobs, queues, the estimated time left, and buttons to retry failures.' },
        {
          actor: 'ext',
          label: 'What people say on Reddit',
          detail: 'Built, off until connected. Every 30 minutes, popular posts with 5+ comments are matched to a story by link or by meaning, or ignored. The top 40 comments are summarised with a mood, and every quote is checked word for word.',
          planned: true,
        },
        { actor: 'app', label: 'Collection through your own VPN', detail: 'Designed, not built yet.', planned: true },
      ],
      outputs: ['Dashboard, map, stories, search, reports'],
    },
  ],
};

const ro: WorkflowSet = {
  intro:
    'COUNSELOR rulează opt fluxuri pe serverul tău. Cele mai multe pornesc singure, după program; celelalte pornesc când deschizi un ecran sau ceri ceva. Alege unul ca să-l urmărești pas cu pas.',
  workflows: [
    {
      id: 'collect',
      title: 'Colectarea știrilor',
      trigger: 'La fiecare 5 minute; fiecare sursă e verificată la 15',
      summary: 'Articolele noi sunt găsite în sursele tale: din fluxul RSS sau, dacă nu există, citind prima pagină a site-ului.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Care surse sunt la rând?', detail: 'O sursă e la rând la 15 minute după ultima verificare. O sursă care tot dă erori așteaptă de două ori mai mult de fiecare dată, până la de 16 ori.' },
        { actor: 'ext', label: 'Cere sursei ce e nou', detail: 'Se cer doar schimbările: o sursă neschimbată răspunde „nemodificat” și nu se mai descarcă nimic. Limită de 30 de secunde.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Are sursa un flux RSS?',
          branches: [{ when: 'Fără flux', then: 'Se citesc legăturile din prima pagină: același site, titlu de minimum 15 caractere, maximum 120 de legături.' }],
          yes: 'Flux: se citesc titlul, legătura, autorul, data și imaginea',
        },
        { kind: 'decision', actor: 'store', label: 'Legătura a mai fost văzută?', branches: [{ when: 'Da', then: 'Sărită.' }], yes: 'Legătură nouă' },
        { actor: 'store', label: 'Salvată ca articol nou', goto: 'read' },
        { actor: 'you', label: 'Adaugi o sursă', detail: 'Lipești orice adresă. Dacă e un flux sau pagina trimite la unul, e adăugată ca RSS; altfel se citește pagina. Dacă nu se găsesc articole, ești anunțat.' },
      ],
      outputs: ['Articole noi, care așteaptă să fie citite'],
      feeds: ['read'],
    },
    {
      id: 'read',
      title: 'Citirea fiecărui articol',
      trigger: 'Imediat după colectare',
      summary: 'Pagina întreagă e descărcată și transformată în text curat, cu imagine și limbă.',
      steps: [
        { actor: 'ext', label: 'Descarcă pagina articolului', detail: 'Limită de 30 de secunde.' },
        { actor: 'app', label: 'Găsește imaginea principală', detail: 'Din etichetele de distribuire ale paginii, înaintea textului, ca și paginile cu abonament să aibă imagine.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Există text lizibil?',
          branches: [{ when: 'Nu (abonament sau pagină doar cu scripturi)', then: 'Merge mai departe doar cu titlul; analiza pe articol îl sare.', tone: 'warn' }],
          yes: 'Text curat extras',
        },
        { kind: 'decision', actor: 'store', label: 'Același text există deja?', branches: [{ when: 'Da', then: 'Marcat ca duplicat; se oprește aici.' }], yes: 'Text nou' },
        { actor: 'app', label: 'Detectează limba', detail: 'Română, engleză, germană, franceză, spaniolă, italiană, rusă sau ucraineană; altfel, limba declarată de sursă.' },
        { actor: 'store', label: 'Păstrează textul, renunță la pagina brută', goto: 'group' },
        { kind: 'loop', actor: 'app', label: 'Dacă descărcarea eșuează', detail: 'Reîncercată de 3 ori, la 2 minute distanță, apoi din nou la fiecare 30 de minute.' },
      ],
      outputs: ['Text curat, imagine și limbă pentru fiecare articol'],
      feeds: ['group'],
    },
    {
      id: 'group',
      title: 'Gruparea în povești',
      trigger: 'Imediat după citirea unui articol',
      summary: 'Articolele despre același eveniment, din orice publicație și în orice limbă, sunt adunate într-o singură poveste.',
      steps: [
        { actor: 'ai', label: 'Transformă articolul într-un vector de sens', detail: 'Titlul plus textul. Modelul e multilingv, așa că o relatare în română și una în engleză despre același eveniment ajung aproape una de alta.' },
        { actor: 'store', label: 'Caută articolele cele mai apropiate', detail: 'Printre articolele publicate cu cel mult 72 de ore înainte sau după acesta.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Destul de asemănătoare (0,78 sau mai mult)?',
          branches: [{ when: 'Nu', then: 'Începe o poveste nouă cu acest articol.' }],
          yes: 'Intră în acea poveste (dacă nu e retrasă)',
        },
        { actor: 'app', label: 'Povestea e marcată pentru analiză', detail: 'Poveștile doar primesc articole; nu sunt niciodată despărțite sau regrupate.', goto: 'understand' },
        { kind: 'loop', actor: 'app', label: 'Plasa de siguranță dinaintea fiecărei sinteze', detail: 'Articolele rămase singure 45 de minute sunt potrivite după cuvintele din titlu: cel puțin o treime în comun și minimum 2 cuvinte comune.' },
      ],
      outputs: ['Povești care urmăresc un eveniment în toate publicațiile'],
      feeds: ['understand'],
    },
    {
      id: 'understand',
      title: 'Înțelegerea fiecărei povești',
      trigger: 'Verificat la fiecare 3 minute',
      summary: 'Când o poveste s-a așezat, AI-ul local îi citește articolele și scrie ce s-a întâmplat, ce se știe și ce nu.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Care povești sunt gata?', detail: 'Gata când o relatează 2 sau mai multe publicații, sau după 20 de minute. Până la 100 odată, mai ales cele mai noi.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Câte publicații?',
          branches: [
            { when: 'Una', then: 'Modelul mic, fără puncte de vedere sau consens, ca să nu inventeze un contrast.' },
            { when: 'Mai multe', then: 'Modelul mare.', tone: 'ok' },
          ],
          yes: 'Apoi',
        },
        { actor: 'ai', label: 'Citește până la 15 articole', detail: 'Câte 2.000 de caractere din fiecare, cu orientarea politică cunoscută a fiecărei publicații.' },
        {
          actor: 'ai',
          label: 'Scrie analiza',
          detail: 'Rezumat scurt, mediu și detaliat; faptele principale; ce știm și ce nu știm; puncte de vedere; citate; persoane, organizații și locuri; 1–3 categorii. Țara evenimentului stabilește regiunea.',
        },
        { actor: 'app', label: 'Măsoară, fără AI', detail: 'Cum se împart publicațiile pe spectru și un scor de încredere din numărul de surse și de orientări.' },
        { actor: 'store', label: 'Salvează noua versiune', detail: 'Cea anterioară rămâne în istoricul poveștii.', goto: 'score' },
        { kind: 'loop', actor: 'app', label: 'Analizată din nou când crește', detail: 'După 45 de minute de liniște și cu cel puțin 50% mai multe articole. Inactivă 48 de ore: retrasă.' },
        {
          actor: 'ai',
          label: 'Fiecare articol, în paralel',
          detail: 'La fiecare 5 minute, modelul mic scrie pentru fiecare articol un rezumat neutru, încadrarea lui (stânga, centru sau dreapta, și de ce), 2–4 afirmații verificabile și un titlu în română. Erorile sunt reîncercate de până la 3 ori.',
          goto: 'factcheck',
        },
      ],
      outputs: ['Rezumate în trei lungimi', 'Ce știm / ce nu știm', 'Puncte de vedere și citate', 'Spectrul surselor și încrederea'],
      feeds: ['score', 'factcheck'],
    },
    {
      id: 'score',
      title: 'Importanță și alerte',
      trigger: 'După fiecare analiză de poveste',
      summary: 'Fiecare poveste primește un scor de importanță de la 0 la 100; cele importante ajung la tine ca alertă.',
      steps: [
        {
          actor: 'app',
          label: 'Calculează importanța, aritmetic',
          detail: 'Surse până la 30 de puncte, credibilitatea surselor 15, țări implicate 15, guvern sau armată 15, bani 10, categoriile tale 10, viteza de răspândire 5.',
        },
        { kind: 'decision', actor: 'app', label: 'Peste pragul tău?', branches: [{ when: 'Sub (implicit 60)', then: 'Rămâne în panou, fără alertă.' }], yes: 'Peste' },
        { kind: 'decision', actor: 'store', label: 'Există deja o alertă pentru ea?', branches: [{ when: 'Da', then: 'Nicio a doua alertă.' }], yes: 'Prima dată' },
        { actor: 'ai', label: 'Scrie de ce contează', detail: 'Una sau două fraze de la modelul mare; o frază standard dacă eșuează.' },
        { actor: 'app', label: 'Trimite alerta', detail: 'O notificare pe dispozitivele tale și un e-mail, dacă e configurat. Aplicația deschisă o arată și ea.' },
        { actor: 'app', label: 'Niveluri de importanță', detail: 'Critic, ridicat, crescut și normal sunt relative: primele 3%, 10% și 25% dintre poveștile curente.' },
      ],
      outputs: ['Alerte pe telefon și calculator', 'Un scor de importanță pe fiecare poveste'],
    },
    {
      id: 'briefing',
      title: 'Scrierea sintezei',
      trigger: 'Zilnic la 07:00, la fiecare 4 ore sau când ceri',
      summary: 'Un raport pe perioadă: poveștile principale, România și lumea, analize aprofundate și verificări.',
      steps: [
        { kind: 'schedule', actor: 'app', label: 'Alege perioada', detail: 'Sinteza de dimineață acoperă 24 de ore; cele periodice ultimele 6 ore; sau orice zi alegi.' },
        { actor: 'app', label: 'Grupează articolele rămase singure' },
        { actor: 'app', label: 'Ordonează poveștile', detail: 'Primele 5 din fiecare categorie și cele mai importante 13 în total.' },
        {
          actor: 'ai',
          label: 'Scrie raportul',
          detail: 'Modelul mare scrie rezumatul și analizele aprofundate: ce s-a întâmplat, de ce contează, unde diferă publicațiile, ce rămâne neclar. Dacă eșuează, tot se produce o privire de ansamblu din date.',
        },
        { actor: 'ai', label: 'România și Internațional', detail: 'Două secțiuni separate, ca știrile din România să nu fie înghesuite în zilele aglomerate.' },
        { actor: 'app', label: 'Verifică afirmațiile', goto: 'factcheck' },
        { actor: 'app', label: 'Numărate, nu scrise', detail: 'Dovezile din spatele fiecărei analize, ce s-a schimbat de la sinteza anterioară și subiectele emergente vin direct din date.' },
        { actor: 'store', label: 'Salvează cu număr de referință', detail: 'De exemplu RAP-2026-09-26-M01. PDF-ul se generează când îl descarci.' },
      ],
      outputs: ['Sinteza pe ecran', 'PDF', 'Subiecte emergente', 'Verificări'],
      feeds: ['factcheck'],
    },
    {
      id: 'factcheck',
      title: 'Verificarea afirmațiilor',
      trigger: 'În fiecare sinteză',
      summary: 'AI-ul propune afirmațiile de verificat, dar fiecare verdict e decis de cod, din ce au relatat alte publicații.',
      steps: [
        { actor: 'ai', label: 'Se propun afirmații', detail: 'Modelul mare sugerează afirmațiile de verificat. Orice verdict oferit de el e ignorat.' },
        { actor: 'store', label: 'Caută relatări potrivite', detail: 'Fiecare afirmație e comparată cu afirmațiile extrase din articolele analizate, în 72 de ore, păstrând potrivirile de 0,72 sau mai mult.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Poate conta fiecare citat?',
          branches: [{ when: 'Publicație necunoscută', then: 'Eliminat, în loc să fie citat sub un nume ghicit.', tone: 'bad' }],
          yes: 'Se păstrează cel mai puternic citat din fiecare publicație',
        },
        { actor: 'ai', label: 'Etichetează fiecare citat', detail: 'Susține afirmația, o contrazice sau nu are legătură. Modelului i se cere să nu decidă verdictul.' },
        {
          kind: 'decision',
          actor: 'app',
          label: 'Verdictul, decis de cod',
          branches: [
            { when: 'Există o contrazicere', then: 'Contestat, cu cine o contrazice.', tone: 'warn' },
            { when: 'Două sau mai multe o susțin', then: 'Confirmat.', tone: 'ok' },
            { when: 'Una o susține', then: 'O singură sursă.' },
            { when: 'Niciuna', then: 'Neverificabil, inclusiv când încă nu există dovezi.' },
          ],
        },
      ],
      outputs: ['Un verdict pentru fiecare afirmație, cu publicațiile din spate'],
    },
    {
      id: 'screens',
      title: 'Ecranele tale',
      trigger: 'Oricând deschizi aplicația',
      summary: 'Ce vezi și cum se actualizează singur.',
      steps: [
        { actor: 'you', label: 'Panoul principal', detail: 'Fiecare secțiune se reîmprospătează singură (alertele la fiecare minut, panoul AI la 10 secunde) și se oprește când fila e ascunsă.' },
        {
          actor: 'app',
          label: 'Harta lumii',
          detail: 'Fiecare poveste e pusă în țara ei: întâi din titlu, apoi după cele mai rare locuri menționate. Poveștile fără țară nu apar pe hartă. Poveștile noi necitite (sub 6 ore) clipesc, până la 12.',
        },
        { actor: 'you', label: 'O poveste', detail: 'Marcată ca citită după 1,5 secunde. Orice etapă de analiză poate fi reluată.' },
        { actor: 'you', label: 'Căutare, salvate și de citit mai târziu', detail: 'Cauți după cuvinte din titluri, persoane și rezumate.' },
        { actor: 'app', label: 'Ce face AI-ul', detail: 'Sarcinile în lucru, cozile, timpul estimat rămas și butoane pentru reluarea erorilor.' },
        {
          actor: 'ext',
          label: 'Ce spun oamenii pe Reddit',
          detail: 'Construit, oprit până la conectare. La fiecare 30 de minute, postările populare cu 5+ comentarii sunt potrivite cu o poveste după legătură sau după sens, altfel ignorate. Primele 40 de comentarii sunt rezumate, cu starea de spirit, iar fiecare citat e verificat cuvânt cu cuvânt.',
          planned: true,
        },
        { actor: 'app', label: 'Colectare prin propriul VPN', detail: 'Proiectată, încă neconstruită.', planned: true },
      ],
      outputs: ['Panou, hartă, povești, căutare, rapoarte'],
    },
  ],
};

export default { en, ro };
